### ISSUE TITLE
[BUG]: Notifications pop up LSSM 4.4.1

### ISSUE THREAD

**Issue by Lucgaming19** [LSS-Manager/LSSM-V.4#1026]
When I enable notifications I don't get the pop up any more. This was working but isn't any more I didn't change any thing.

**How to reproduce?**
1. go to the appstore tab of the LSSM extension enable notifications
2. go to settings tab in the LSSM extension
3. open the notification settings 
4. add a notification (I have when a new incident occurs pop up (collor is red)
5. save the settings and wait for incident (no pop up comes after refresh als not)
6. The error occured

**Expected behavior**
What did you expect LSS-Manager to do?
when the event happens the pop up should be visible

**Further notes:**
 - OS: Windows 10 Pro 20H2	19042.1348   Windows Feature Experience Pack 120.2212.3920.
 - Browser: Google chrome
 - LSSM-Version: 4.4.1+20211120.0054 [stable]
 - for Smartphones / Tablets: your device: 
 - which of the games are you playing: Meldkamerspel
 - your ingame name: Lucgaming16

**Comment by jxn-30** [comment]
We have already fixed that for betas. It will be fixed for stable users within the next days.
However: Thanks for your report!

**Comment by Lucgaming19** [comment]
> We have already fixed that for betas. It will be fixed for stable users within the next days. However: Thanks for your report!

thank u for the fast awnser. I'm looking forward to the publishing of the update.

**Comment by jxn-30** [comment]
Is fixed with #1029 (Release 4.4.2)
