### ISSUE TITLE
[Feature Request]: Aufgabenliste unterteilen

### ISSUE THREAD

**Issue by minerop5000** [LSS-Manager/LSSM-V.4#1087]
**Geht deine Idee aus einer Problemstellung hervor?**
![grafik](https://user-images.githubusercontent.com/75438446/145617419-b9711566-3ed4-4104-aab7-19bdd1078a53.png)
aufgabenansicht ist unübersichtlich, wenn mehrere events mit eigenen zählern und deren aufgaben existieren

**Lösung / Feature**
die liste in 2 sektionen unterteilen (möglicherweise auch jeweils zum ein und ausklappen)
 - einmal für die aufgaben
 - für die  "Erledige X <event> Event-Aufgaben"

**Comment by jxn-30** [comment]
Das Redesign hat diese Funktionalität nun implementiert, wenn in den Einstellungen die Aufgaben aktiviert sind.
