### ISSUE TITLE
[BUG]: Discord invite links invalid

### ISSUE THREAD

**Issue by itayo** [LSS-Manager/LSSM-V.4#1202]
Currently the invite inks for the disord is invalid and is not accepted.
please update the link

**Comment by jxn-30** [comment]
which one is invalid?
We did not invalidate any of the old links.

**Comment by itayo** [comment]
it is time based. a Discord invite link only has a certain ttl. but i cant join as the links for the invites are invalid both here and on wiki

**Comment by jxn-30** [comment]
https://discord.gg/RcTNjpB is the official invite link and is not time-based. Any links that I can find on both, here GitHub and the Wiki all do show this link.
![grafik](https://user-images.githubusercontent.com/27238105/150695990-bac20089-b7e1-47de-a1ff-c348160a5504.png)

**Comment by itayo** [comment]
for some reason it diditn work for me until u posted. here im closing this issue as invalid. sorry for the issue
