### ISSUE TITLE
[BUG]: building hover wont load properly.

### ISSUE THREAD

**Issue by Cr4zyc4k3** [LSS-Manager/LSSM-V.4#127]
**Describe what happens**
building hover wont load buildings properly after building it. It will shown as "Verband" if you hover over it. Hard reload fixed it after 3. attempt.

**How to reproduce?**
1. Buy a new building
2. Hover over it

**Screenshots**
![Screenshot (15)](https://user-images.githubusercontent.com/69073372/96419414-66d72400-11f4-11eb-8e68-da283253bd5e.png)

**Further notes: *(please complete)***
 - OS: Windows 10 19041.572
 - Browser: Firefox 81.0.2 (64-Bit)
 - LSSM-Version: 4.0.6+20201015.2223 [beta] 
 - your ingame name: Crazycake

**Further**
Not sure whether its a bug or a caching problem

**Comment by KBOE2** [comment]
We just don't include new buildings and vehicles yet directly after buying them.


But will be done hopefully before beta release

**Comment by jxn-30** [comment]
@Cr4zyc4k3 should be fixed with Beta-Build `4.1.9+20210102.1510` please check and close if fixed.

**Comment by Cr4zyc4k3** [comment]
Is fixed
