### ISSUE TITLE
[BUG]: Enhanced POI - Filteroptions vanish

### ISSUE THREAD

**Issue by CSA-Verweigerer** [LSS-Manager/LSSM-V.4#128]
When opening POI-stting mode, there is a menu where I can filter the types of POI I want to be displayed.
After setting the first POI the Menu is gone

**How to reproduce?**
Explain here what you did when the error occured
for example:
1. click "Neuen POI setzen" => Menu is visible
2. click "Speichern" => Menu is gone 

**Expected behavior**
Menu should be visible even after setting a POI

**Screenshots**
If possible, add screenshots here to visualize the bug
before:
![grafik](https://user-images.githubusercontent.com/29802197/96442168-fa1b5400-120a-11eb-98b1-36ac2a595eaa.png)
after:
![grafik](https://user-images.githubusercontent.com/29802197/96442215-0c958d80-120b-11eb-9fb7-a74d6d9977bd.png)

**Further notes: *(please complete)***
 - OS: Windows 10
 - Browser: Vivaldi
 - LSSM-Version: 4.0.6
 - which of the games are you playing: LSS Standard
 - your ingame name: CSA-Verweigerer

**Further**
Add further notes here

**Comment by KBOE2** [comment]
@CSA-Verweigerer please clear your browser cache and have a look if the bug is fixed!

**Comment by CSA-Verweigerer** [comment]
Yes, I retested it and now it works as planned 

Gott work (as always) thank you!!!
