### ISSUE TITLE
[Feature Request]: Quick Filter Buttons in Missionlist

### ISSUE THREAD

**Issue by JanSuerth** [LSS-Manager/LSSM-V.4#1332]
**Is your feature request related to a problem?**

A. Currently you only have the * or Person to show you if you are already part of a alliance mission which requires you to look through the entire list if you are missing out on something. 

B. Your own calls can get quit full, if you have already send all units to a call but it just needs some time to finish up it's unnecessary to see those in the list. 

**Solution / Feature**

- [ ] A. A button to filter out all missions that you are already a part of. This should be quickly accessible so that you can quickly check if you are missing something and then return to the full list. 

- [ ] B. A button to filter all your own complete missions out of the list (all the green once). 

**Alternatives**
This also could be tied into a larger filter menu (which I heard is already planned) but would have the downside of not being accessible by just one click. 

**Additional**
https://i.imgur.com/SjibhBc.png

**Comment by jxn-30** [comment]
The filters that are planned for #11 will be available with one click. Or at least you will be able to mark filters to be available with a single click ;)
