### ISSUE TITLE
[BUG]: Fahrzeuganforderungen werden nicht geladen

### ISSUE THREAD

**Issue by DerOetzi** [LSS-Manager/LSSM-V.4#1337]
Bei vielen meiner Einsätze bleibt die rote Box mit den Benötigten Fahrzeugen leer. Vermutlich die wo ein DGL benötigt wird

**Wie kann man den Fehler reproduzieren?**
1. Auf Alarm klicken
2. Benötigte Fahrzeuge bleibt leer

**Erwartetes Verhalten**
Welches Verhalten hättest du erwartet?
Anzeige der benötigten Fahrzeuge

**Screenshots**
![image](https://user-images.githubusercontent.com/2345662/160118963-d787b9c6-f338-4e75-b0c1-119db90c2940.png)

**Sonstige Hinweise: *(bitte ergänzen)***
 - Betriebssystem: Linux
 - Browser: Chrome
 - LSSM-Version: [4.5.5](https://github.com/LSS-Manager/LSSM-V.4/releases/tag/v4.5.5)
 - bei Smartphones / Tabletts: Gerät:
 - Welches der Spiele spielst du?: Leistellenspiel
 - Dein Name im Spiel: DerOetzi

**Sonstiges**
Ist seit dem in den Nachrichten angekündigten DGL Update so

**Comment by jxn-30** [comment]
Ich konnte das gerade in Chrome nicht reproduzieren, deshalb benötige ich mehr Infos:
* Welche Chrome-Version nutzt du?
* Bitte öffne einmal die Konsole (F12→Konsole) und dann den Einsatz öffnen.
  Tauchen in der Konsole Fehler (rot) auf, wenn ja welche?
* Welche Einstellungen hast du für den Einsatzhelfer gesetzt?
* Wenn du mit der Maus über den "Hilfe zu diesem Einsatz"-Knopf fährst, steht in der angezeigten URL etwas von `overlay_index` oder `additional_overlays`? Wenn ja, was genau steht da drin?

**Comment by DerOetzi** [comment]
> Ich konnte das gerade in Chrome nicht reproduzieren, deshalb benötige ich mehr Infos:
> 
> * Welche Chrome-Version nutzt du?
99.0.4844.51
> * Bitte öffne einmal die Konsole (F12→Konsole) und dann den Einsatz öffnen.
Keine Fehler in der Konsole
>   Tauchen in der Konsole Fehler (rot) auf, wenn ja welche?
> * Welche Einstellungen hast du für den Einsatzhelfer gesetzt?
![image](https://user-images.githubusercontent.com/2345662/160121425-52a87871-76e7-44a7-9b81-a50feaf4e255.png)
![image](https://user-images.githubusercontent.com/2345662/160121493-d42494a5-3a7a-424a-82a5-74f5c82662f3.png)

> * Wenn du mit der Maus über den "Hilfe zu diesem Einsatz"-Knopf fährst, steht in der angezeigten URL etwas von `overlay_index` oder `additional_overlays`? Wenn ja, was genau steht da drin?
https://www.leitstellenspiel.de/einsaetze/535?mission_id=2355094036&overlay_index=0

Ich glaube es könnte ein temporäres Problem sein ich glaube es betrifft nur Einsätze die vor dem Update schon in meiner Liste waren. Die neuen von heute scheinen wieder sauber zu gehen.

**Comment by jxn-30** [comment]
Ja, ich hab das auch eben feststellen müssen:
Das ganze liegt leider an der spielseitigen Umstellung der DGL-Einsätze.
Wir können das blöderweise nicht umgehen, aber ich hab das eben auch in einem kurzen Info-Post erklärt: https://forum.leitstellenspiel.de/index.php?thread/19176-lss-manager-v-4/&postID=447171#post447171

Damit schließe ich hier, da nicht fixbar und auch nur temporär ;)
