### ISSUE TITLE
[BUG]: Erweiterte Gebäudeansicht Fehler bei Ausbauten direkt anzeigen

### ISSUE THREAD

**Issue by monstalein** [LSS-Manager/LSSM-V.4#1386]
**Verhalten beschreiben**
Die Option "Ausbauten direkt anzeigen" ist aktiviert, es werden in der Gebäudeansicht aber nur fertige Ausbauten als solche angezeigt, alle anderen haben den Status "Noch nicht gebaut", obwohl teilweise der Ausbaut schon läuft.

**Wie kann man den Fehler reproduzieren?**
Ein Gebäude öffnen, bei dem mind. 1 Ausbaut gerade gebaut wird.

**Erwartetes Verhalten**
Die Ausbauten, die gerade gebaut werden, sollen wir gelb mit entsprechendem Text (und evtl. Countdown) angezeigt werden.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/3227357/163153577-6cd6d37d-93cd-47d2-860f-c5736c23005f.png)

**Sonstige Hinweise: *(bitte ergänzen)***
 - Betriebssystem: Windows 10
 - Browser: FireFox 99.0
 - LSSM-Version: 4.5.7+20220412.1215 [stable]
 - Welches der Spiele spielst du?: leitstellenspiel.de
 - Dein Name im Spiel: Monstalein

**Sonstiges**
.

**Comment by Suchty112** [comment]
Ja die Entwickler haben gestern im rahmen eines Contentpacks in einem anderen Land, die bezeichnungen für den countdown geändert. Wir wissen über die Änderung jetzt bescheid und sind dabei dies zu beheben :) 
Ein schönes Osterfest trotzdem gewünscht :)

**Comment by jxn-30** [comment]
Ist mit 16818d9 behoben und wird mit dem nächsten Release für alle online gehen. Dann wird hier auch geschlossen werden.

**Comment by jxn-30** [comment]
Der Bugfix ging gestern mit #1408 für alle nutzer online.
=> close
