### ISSUE TITLE
[Feature Request]: docs: vuepress-plugin-clipboard can working in latest vuepress

### ISSUE THREAD

**Issue by Zhengqbbb** [LSS-Manager/LSSM-V.4#1520]
**Is your feature request related to a problem?**
Write a clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Solution / Feature**
upgrade vuepress-plugin-clipboard to `v2.1.0`
compatible with latest vuepress
https://github.com/LSS-Manager/LSSM-V.4/blob/d3153b66da530bed3754bcf29b8f40d84055b5d0/docs/.vuepress/package.json#L15

https://github.com/LSS-Manager/LSSM-V.4/blob/d3153b66da530bed3754bcf29b8f40d84055b5d0/docs/.vuepress/config.ts#L302

**Additional**
Hi i am the author of vuepress-plugin-clipboard, sorry for the late compatibility, thank you for your support, if you have any other questions, please contact me

**Comment by jxn-30** [comment]
Hey, thanks for informing us! 😊
renovate also proposed the update some minutes ago (#1480) but I will trigger an update right now.

**Comment by Zhengqbbb** [comment]
> 嘿，谢谢你通知我们！😊 renovate 也在几分钟前提出了更新（#1480），但我现在会触发更新。

upgrade vuepress-plugin-clipboard to v2.1.0 !!!!!!
hhh. i updated README.

**Comment by jxn-30** [comment]
updated with #1522
