### ISSUE TITLE
[BUG]: Fehlermeldung wegen Update auf 4.5.10, aber es ist bereits installiert

### ISSUE THREAD

**Issue by happy007fl** [LSS-Manager/LSSM-V.4#1540]
**Verhalten beschreiben**
Füge hier eine detaillierte Beschreibung ein, was genau passiert.

**Wie kann man den Fehler reproduzieren?**
Beschreibe hier, wenn möglich, was du gemacht hast, als der Fehler auftrat.
z.B.:
1. Wenn ich einen Alarm anklicke, öffnet sich das entsprechende Fenster
2. dann erscheint ein 2. kleineres Fenster mit der Meldung
Userscript veraltet
Lieber LSSM-Nutzer,
leider ist dein LSSM V.4 Userscript veraltet. In der neuesten Version wurden änderungen am Userscript vorgenommen, die wichtig für die Funktion des LSSM V.4 sind.
Du benötigst mindestens Version 4.5.10, das Update kannst du bequem per Klick auf [lssm-v4.user.js](https://proxy.lss-manager.de/v4/lssm-v4.user.js) durchführen.

Liebe Grüße,
Dein LSSM-Team
3. ich kann dann das Fenster mit dem Anklicken auf OK schliessen und den Auftrag abschliessen
4. Beim Aufruf eines neuen Alarms erscheint die gleiche Meldung wieder
5. Ich habe bereits 3X das Update nochmals aufgeführt, installierte Version ist: 4.5.10+20220527.0001 [stable]

**Erwartetes Verhalten**
Welches Verhalten hättest du erwartet? dass das Update Fenster nicht mehr erscheint

**Screenshots**

**Sonstige Hinweise: *(bitte ergänzen)***
 - Betriebssystem: Windows 11
 - Browser: Google Chrome
 - LSSM-Version: 4.5.10+20220527.0001 [stable]
 - bei Smartphones / Tabletts: Gerät:
 - Welches der Spiele spielst du?: Leitstellenspiel
 - Dein Name im Spiel: happy007fl

**Sonstiges**
Füge hier sonstige Hinweise ein.

**Comment by jxn-30** [comment]
Es zählt die Version vom Userscript (in Tampermonkey). Dort muss 4.5.10 stehen.
Leider scheint Tampermonkey das Update nicht immer richtig auszuführen.

Am besten bearbeitest du das Script direkt in Tampermonkey und fügst dort den Inhalt von https://proxy.lss-manager.de/v4/static/lssm-v4.user.js#bypass=true ein. Das sollte helfen.

**Comment by jxn-30** [comment]
Wir haben heute Nacht die Texte im Popup nochmals ein bisschen verbessert, sodass zusätzliche Hilfestellungen gegeben werden, sollte das einfache Update nicht klappen.

Hat das Userscript-Update bei dir mittlerweile funktioniert?

**Comment by happy007fl** [comment]
Guten Morgen,
Habe heute morgen das Userscript-Update nochmals durchgeführt, nun hat es geklappt.
Danke und Grüsse

**Comment by jxn-30** [comment]
Super, dann schließe ich hier.
Beim nächsten mal sollte es dann hoffentlich zu weniger Problemen kommen.
