### ISSUE TITLE
Probleme bei Gebäude bauen (Mozilla Firefox,LSSM V4)

### ISSUE THREAD

**Issue by keksi27bln** [LSS-Manager/LSSM-V.4#1542]
Ich möchte Gebäude bauen wähle den Standort aus vergebe ein Name und vergebe Leitstelle und das Fahrzeug.

Wenn ich dann per Credits kaufe, sind die Buttons hellgrün hinterlegt, ich kann kein neues Gebäude bauen , erst wenn ich auf Zurück klicke

Des öfteren habe ich auch schon eine Fehler Meldung erhalten 
---------------------------
Fehlerhafte Anfrage: Status 409

Huch, bei dieser Serveranfrage ist leider ein Fehler
aufgetreten:
Status: 409 Conflict
URL: POST https://www.leitstellenspiel.de/buildings
Feature: generalExtensions-newBuildung
Dauer: 2396ms
User : XXXXXX <-- meine UserID normaler weise
Timestamp: 2022-05-28T19:47:15.456Z
....bitte später nochmal probieren

Habe nun alle funktionen aus dennoch tritt der fehler auf, wenn ich aber den LSS Manager V4 ganz deaktiviere in Tampermonkey , kann ich bauen bezahlen und gleich weiter neues Gebäude setzen

**Comment by jxn-30** [comment]
Mit dem nächsten Release wird der Bug gefixed sein. Mit Commit 061c55c ist dieser bereits jetzt für Betas gefixed!
Sollte es dann zu einem Fehler beim Bauen kommen, wird der Button wieder anklickbar sein. Sind sie das nicht, sind nicht alle Eingaben vollständig, z.B. kann es sein, dass der Name fehlt oder unvollständig ist.
