### ISSUE TITLE
[Feature request]: Umbenennen der Kartenlesezeichen

### ISSUE THREAD

**Issue by RagingLightning** [LSS-Manager/LSSM-V.4#1791]
### Is your feature related to a problem?

Nein, es handelt sich einzig um eine Erweiterung

---

No, this is only an idea for extended functionality

### Solution / Feature

Ich wünsche mir eine Funktion, die es ermöglicht, mehrere Kartenansichten nach dem Schema der Startansicht der verbesserten Karte erstellen zu können. Dies ist insbesondere dann interessant, wenn mehrere Leitstellen und folglich Landkreise bebaut sind. So ließe sich mit einem (oder auch zwe) Klicks bei einem eingehenden Einsatz auf den entsprechenden Landkreis wechseln, um so koordinieren zu können.

---

I'd love to see the ability to set multiple map presets, like the one we can define via the extended map already, and being able to switch between them. This is especially useful, when dealing with many Command Centers and Counties, once an emergency call comes in, one could in one (or maybe two) clicks switch over to the applicable area and manage the forces from there.

**Comment by jxn-30** [comment]
Im Modul "Allgemeine Verbesserungen" gibt es eine Möglichkeit, sich Lesezeichen auf der Karte zu setzen, das müsste doch genau der Wunsch sein, oder?
Historisch bedingt befindet sich das nicht im Karten-Modul und das zu verschieben ist auch nicht ganz trivial.

**Comment by RagingLightning** [comment]
Alles klar, die Funktion habe ich gefunden.

Allerdings kommt dann sofort der Wunsch auf, die Lesezeichen umbenennen zu können... (Es sei denn, ich bin auch hier zu blöd, die Option zu finden :D)

**Comment by jxn-30** [comment]
Nein, so eine Option gibt es noch nicht. Ist aufgenommen auf die Liste der guten Vorschläge :)

**Comment by jxn-30** [comment]
Das ganze geht gerade für Betas online und wird dann mit dem nächsten Release auch für alle Nutzer öffentlich gehen.
