### ISSUE TITLE
[BUG]: [ecw] personal and prisoner transport are not handled properly

### ISSUE THREAD

**Issue by Cr4zyc4k3** [LSS-Manager/LSSM-V.4#184]
**Describe what happens**
The module "extended call window" cant handle required personal/missing water properly. It just shows the String "Wir benötigen noch min" and zeros for selected, on mission, required, et al. The rest of the string is shown like without LSSM. 
If water is missing it shows the right amount of missing water, but the vehicle type is "l". Over the table is written "Wasser" as normal.

**How to reproduce?**
Enable the "extended call window" module in LSSM and the option to beautify missing vehicles.
Get any mission where some minimal amount of personal is required/missing water (eg. mission id 572 or 131).
Trigger the missing vehicle-box. Now the String will destory the table.

**Expected behavior**
Hopefully fix it.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/69073372/97475891-15ded280-194e-11eb-953c-37145923afa6.png)
![grafik](https://user-images.githubusercontent.com/69073372/97478384-293f6d00-1951-11eb-9e81-b3dec56a96ea.png)
![grafik](https://user-images.githubusercontent.com/69073372/97479240-52acc880-1952-11eb-9225-19cc6e419f35.png)

**Further notes: *(please complete)***
 - OS: Win10 pro 19041.572
 - Browser: Firefox 82.0.1 (64-Bit)
 - LSSM-Version: 
 - which of the games are you playing: leitstellenspiel.de
 - your ingame name: Crazycake (264361)

**Comment by KBOE2** [comment]
Also happens for prisoners. See ![](https://media.discordapp.net/attachments/769478594505342996/772572540618407976/unknown.png)
*adjusted title accordingly*

**Comment by jxn-30** [comment]
the `water` part should be fixed with 2c890e0

**Comment by jxn-30** [comment]
staff is supported with 925c338 (and 55c4fd8) as well as b638510
Currently de_DE only, translations for other languages are still to be done.
