### ISSUE TITLE
[Idea] Code of Conduct

### ISSUE THREAD

**Issue by KokosnussDEV** [LSS-Manager/LSSM-V.4#185]
Since the @LSS-Manager team is working with a rather big community of contributors it's time to introduce a Code of Conduct.

### What is a Code of Conduct?
1. A Code of Conduct is a file placed in the projects root folder as `CODE_OF_CONDUCT.md`
2. It's a ["document that establishes expectations for behavior"](https://opensource.guide/code-of-conduct/#why-do-i-need-a-code-of-conduct)
3. It is something all contributors (including admins) should respect and maintain.
Basically, it's a set of rules and [you can read more about what a Code of Conduct is](https://opensource.guide/code-of-conduct/#why-do-i-need-a-code-of-conduct).

Here are 3 examples of very well made Code of Conducts:
The [Django Code of Conduct](https://www.djangoproject.com/conduct/) ([the Enforcement](https://www.djangoproject.com/conduct/enforcement-manual/))
The most used: [Contributor Covenant](https://www.contributor-covenant.org/version/1/4/code-of-conduct/)
The one with a good way to report violations: [khmer Code of Conduct](https://github.com/dib-lab/khmer/blob/HEAD/CODE_OF_CONDUCT.rst)

### What should we do with all this information in mind?
We should write our own Code of Conduct or adopt one (or do nothing?) to enforce some basic rules to remind us to respect each of us!

**Comment by Suchty112** [comment]
@LSS-Manager/developers test commit

**Comment by KokosnussDEV** [comment]
What I would propose is a mix of all the CoC listed above and add some tweaks that fit LSSM to it

**Comment by KokosnussDEV** [comment]
Closed by #195
