### ISSUE TITLE
[BUG]: Redesign errors on coastal rescue transport request

### ISSUE THREAD

**Issue by mz045** [LSS-Manager/LSSM-V.4#1990]
### What happened?

Fehler tritt auf in der amerikanischen Version des Moduls Redesign beim Einsatz "Overturned Small Vessel" (https://www.missionchief.com/einsaetze/728).
Beim Patiententransport erscheint eine Fehlermeldung und der Patient kann nicht transportiert werden.
Wenn das Modul deaktiviert wird, dann funktioniert der Transport.
![error](https://user-images.githubusercontent.com/119636217/205181354-92eadb8c-a80c-4991-b59b-72d62e70933d.jpg)

### Wie kann man den Fehler reproduzieren?

1. Auf 'Transport requested' klicken
2. Das Fehlverhalten tritt auf

### Erwartetes Verhalten

erfolgreicher Patiententransport

### System

- Betriebssystem: Windows 10
- Browser und version: Google Chrome 107.0.5304.122 (Offizieller Build) (64-Bit)
- LSSM-Version: 4.7.0+20221126.2133 [stable]
- Spiel-Version: [MC-en_US] 🇺🇸 missionchief.com

**Comment by jxn-30** [comment]
Das liegt leider an der "Patienten übergeben"-Geschichte. Wir warten hier gerade noch auf ein spielseitiges Update, welches uns eine effektive Fehlerbehebung ermöglicht.
Aktuell hilft da leider nur bei solchen Sprechwünschen, bei denen Patienten erst zu einer Station an Land übergeben werden, das Redesign für Fahrzeuge temporär auszuschalten.

**Comment by jxn-30** [comment]
There is a preview-branch for testing the bugfix available now: `pr2017`

We will merge into beta tomorrow and release on stable on friday.
