### ISSUE TITLE
[Feature Request]: Option to refresh all staging areas

### ISSUE THREAD

**Issue by wgheath** [LSS-Manager/LSSM-V.4#1999]
### Is your feature related to a problem?

I often have multiple staging areas that I keep up and running.  Instead of having to cycle through each one and hitting the refresh button, it would be nice if you could hit one button to refresh all of them at once.

### Solution / Feature

Set a button in the Stations section to refresh all Staging areas with a single button click - much like was done for the Patrols option that was recently added.

### Alternatives

Any location for this option would be acceptable, it does not need to be in the Stations section.

**Comment by jxn-30** [comment]
got the OK from game team as long as there is a manual interaction required (as suggested).
