### ISSUE TITLE
[BUG]: <modules-extendedCallWindow-components-enhancedMissingVehicles> Foam Trailer not counted for Water Tankers

### ISSUE THREAD

**Issue by JanSuerth** [LSS-Manager/LSSM-V.4#2079]
### What happened?

When having the "enhancedMissingVehicles" component for the "extendedCallWindow" module enabled and selecting a Foam Trailer it is not counted towards Water Tankers. 

### How to reproduce?

1. Have a call with a missing Water Tanker.
2. Select a Foam Trailer
3. Ta-da

### Expected behavior

The Foam Trailer should be counted towards the number of Water Tankers because that is the way the game handles it.

### System

OS: Windows 11
Browser and version: Edge - 109.0.1518.55 (Official build) (64-bit)
LSSM-Version: 4.7.3+20230115.1624 [stable]
Game-Version: https://www.missionchief.com/

**Comment by Gooochy** [comment]
Is fixed in PR here: https://github.com/LSS-Manager/LSSM-V.4/pull/2080/commits/9969c9123fd64051196673f0e12758bd187b8899
