### ISSUE TITLE
[BUG]: [ecw] patientSummary & generationDate remove eachother

### ISSUE THREAD

**Issue by jxn-30** [LSS-Manager/LSSM-V.4#209]
**Describe what happens**
> Ach, und der Generierungszeitpunkt scheint das Patientensummary zu überdecken
by @CSA-Verweigerer 

**How to reproduce?**
1. enable patientSummary & generationDate in ecw
2. open mission with patients where patientSummary will be active
3. only one of both is shown

**Expected behavior**
Step 3: Both shall be shown!

**Screenshots**
–––

**Further notes: *(please complete)***
 - OS: *
 - Browser: * 
 - LSSM-Version: latest
 - for Smartphones / Tablets: your device: *
 - which of the games are you playing: *
 - your ingame name: *

**Further**
–––

**Comment by Tsumiki-Chan** [comment]
@all-contributors please add Tsumiki-Chan for security review question financial

**Comment by Tsumiki-Chan** [comment]
@all-contributors please add @Tsumiki-Chan for security,review,question,financial

**Comment by Tsumiki-Chan** [comment]
@all-contributors please add @Tsumiki-Chan for security
@all-contributors please add @Tsumiki-Chan for review
@all-contributors please add @Tsumiki-Chan for question
@all-contributors please add @Tsumiki-Chan for financial

**Comment by Tsumiki-Chan** [comment]
@all-contributors please add @Tsumiki-Chan for security, review, question and financial

**Comment by jxn-30** [comment]
Thanks for the spam, bot. Locking here for a few hours

**Comment by Ron31** [comment]
Fixed with build [#632.1](https://travis-ci.com/github/LSS-Manager/LSSM-V.4/jobs/435132073)
