### ISSUE TITLE
[Feature request]: New game layouts and more

### ISSUE THREAD

**Issue by sup3r93** [LSS-Manager/LSSM-V.4#2112]
### Is your feature related to a problem?

No

### Solution / Feature

In version 3.0 there were several layouts that changed the position of the map, chat, etc., (as you can see in the images below and in the link present), it would also be nice to insert the list of missions present above (third screen), all game speeds present, and the pause button, so you don't have to enter the appropriate menu every time to change the mission creation speed.

https://imgur.com/5Imj6P0
https://imgur.com/O5V1N1y
3 screen:
https://imgur.com/CWBBe11

![L1](https://user-images.githubusercontent.com/94311785/216626924-3400e8fe-3127-436c-8ca1-04024cd57993.png)
![L2](https://user-images.githubusercontent.com/94311785/216626989-f1ad0523-f8ac-497d-a4f3-ca0687fef0ae.png)
![l3](https://user-images.githubusercontent.com/94311785/216627804-b210e31b-2cb6-4d82-a666-6ef80971d4a3.png)

**Comment by Cr4zyc4k3** [comment]
Already planned see https://github.com/LSS-Manager/LSSM-V.4/issues/372
