### ISSUE TITLE
[Feature request]: 

### ISSUE THREAD

**Issue by bagman002** [LSS-Manager/LSSM-V.4#2249]
### Is your feature related to a problem?

Yes. Due to a recent update with the Australian server with airport firefighting vehicles it now produces non-friendly names like

modules.missionhelper.vehicles.captions.arff
modules.missionhelper.vehicles.captions.riv
2 modules.missionhelper.vehicles.captions.rettungstreppe

Instead of the friendly name of ULFV Crash Tender and so on.

### Solution / Feature

Change non-friendly names with friendly names

**Comment by Suchty112** [comment]
https://github.com/LSS-Manager/LSSM-V.4/commit/71a98c7068a220bb2fdd3bccaeaf5bd42ea68c38
It will be online in the Beta Branch in a few minutes :)
