### ISSUE TITLE
[BUG]: [emv] 🇦🇺 Bushfire vehicles won't count

### ISSUE THREAD

**Issue by bagman002** [LSS-Manager/LSSM-V.4#2256]
### What happened?

I have found that bushfire vehicles (Ultra-Light Tanker, Light Tanker as well as all non-rescue trucks) are not counting towards bushfire vehicles which means the share alliance posts are also not counted when talking with the alliance.

Further more the SES mobile command unit is not getting counted against the mobile command requirement when they are the same.

![image](https://user-images.githubusercontent.com/66065321/230021539-bd209c85-a5b1-40a2-ab60-45921d30a876.png)

### How to reproduce?

1. Go to current mission with bushfire units required
2. Select bushfire units required
3. The error occurred as the bushfire required count does not go green and likewise for SES mobile command

### Expected behavior

Expect bushfire units to count towards bushfire like all other units within the enhanced vehicle view.

### System

- OS: [e.g. Windows 11]
- Browser and version: All Browers Firefox, Edge and Chrome
- LSSM-Version: [both stable and beta versions currently running beta 4.7.4+2020405.0633 due to airport update)
- Game-Version: missionchief.com.au

**Comment by Cr4zyc4k3** [comment]
Hi @bagman002,
can you provide the the IDs for the missing/wrong assigned vehicles or even better, can you add them in /src/modules/extendedCallWindow/i18n/en_AU.json ? That would make it a lot easier for us 😄

**Comment by bagman002** [comment]
Where would I find the vehicle ID's?

**Comment by Cr4zyc4k3** [comment]
Here: https://api.lss-manager.de/en_AU/vehicles or 
https://missionchief.com.au/api/vehicles if you bought the vehicles. (`vehicle_type` is the ID)

**Comment by bagman002** [comment]
I think I did it

**Comment by jxn-30** [comment]
> I think I did it

Thank you!
To get the changes online on beta, please create a new Pull-Request (https://github.com/LSS-Manager/LSSM-V.4/compare/dev...bagman002:LSSM-V.4:patch-1?expand=true). We will then create a preview-build so that you can test wether everything works fine with your changes.

**Comment by Cr4zyc4k3** [comment]
@bagman002 Can you do just the last step to finish your bug fix? Would be a lot easier for us 😄
