### ISSUE TITLE
[BUG]: Hotkey 

### ISSUE THREAD

**Issue by hakoomx** [LSS-Manager/LSSM-V.4#2272]
### What happened?

Wenn ich die Einsatzliste nach Verdienst sortiere (absteigend) und einen Hotkey für "alarmieren und zum nächsten Einsatz" definiert habe, führt der Hotkey nicht zum nächsten Einsatz in der sortierten Liste.

### How to reproduce?

2. Click on '...'
3. Scroll down to '...'
4. ...
5. The error occurred

### Expected behavior

I expect that my hotkey, that says jump to next order jumps to next in sorted list of orders. But actually the hotkey didn't mention if the list is sorted or not.

### System

- OS: [e.g. Windows 10]
- Browser and version: [e.g. Firefox 101.3]
- LSSM-Version: [e.g. 4.6.1+20220917.1751 [stable]]
- Game-Version: [e.g. missionchief.co.uk]

### Additional

Should be independent of the of System I guess this is a global problem.

**Comment by jxn-30** [comment]
Die Hotkeys sind jeweils einmal für "normal durchklicken" und rinmal für "sortiert durchklicken" angelegt.
Es ist nicht geplant, den normalen Hotjey anzupassen, dass er auf die sortierte Variante umschaltet, sobald die Sortierung im Einsatzfenster aktiv ist.

**Comment by hakoomx** [comment]
Hi Jan,hatte nicht gesehen dass es auch Einsatzfenster: Einsatzsortierung Alarmieren und weiter gibt.Die Liste ist wohl alphabetisch sortiert - in finde die User Experience wäre besser wenn direkt unter Einsatzfenster: Alarmieren und weiter direkt käme Einsatzfenster: Einsatzsortierung Alarmieren und weiter.Hab gesehen im Quellcode das würde einiges verkomplizieren - aber ist ja irgendwie immer so - was es für den Enduser einfacher macht ist für den Entwickler komplizierter ;-)
Danke Dir aber für die schnelle Antwort.
Viele GrüßeFrank
    Am Mittwoch, 12. April 2023 um 09:40:42 MESZ hat Jan ***@***.***> Folgendes geschrieben:  
 
 


Die Hotkeys sind jeweils einmal für "normal durchklicken" und rinmal für "sortiert durchklicken" angelegt.
Es ist nicht geplant, den normalen Hotjey anzupassen, dass er auf die sortierte Variante umschaltet, sobald die Sortierung im Einsatzfenster aktiv ist.
