### ISSUE TITLE
[Feature request]: Added permanent search bar

### ISSUE THREAD

**Issue by sup3r93** [LSS-Manager/LSSM-V.4#2308]
### Is your feature related to a problem?

When I open an event tab, and go to the search box, to find a specific vehicle, sometimes it doesn't open

![1](https://user-images.githubusercontent.com/94311785/234855998-4624215d-8907-4f01-b0cb-be4a66b8931e.png)
![2](https://user-images.githubusercontent.com/94311785/234856000-6e95da46-f72b-40d0-a493-a9497ce89cc4.png)

### Solution / Feature

My solution would be to add the ability to leave the search bar always visible, like this

![2](https://user-images.githubusercontent.com/94311785/234856000-6e95da46-f72b-40d0-a493-a9497ce89cc4.png)

**Comment by Cr4zyc4k3** [comment]
Well that's a feature request caused by an error. :smile: 
@sup3r93 Can you open a  new issue for the bug and provide more details (lssm version, lssm config and maybe a video with the bug)? Then we can discuss the enhancement and the problem separately and nobody gets confused

**Comment by sup3r93** [comment]
@Cr4zyc4k3 I tried to reproduce the bug, but until now I haven't been able to, if it recurs, I'll open a specific ticket

**Comment by sup3r93** [comment]
um, sorry I marked it as completed by mistake :)
