### ISSUE TITLE
[Feature request]: Wachen- und Fahrzeug-Benennung

### ISSUE THREAD

**Issue by RazerBean2k18** [LSS-Manager/LSSM-V.4#2311]
### Geht deine Idee aus einer Problemstellung hervor?

Wenn man seine Fahrzeuge umbenennen will, nach komplexen Schemas (Florian Stadt Wache Abteilungsnummer/Funkrufname-Zähler), dann ist nicht nur das eintippen sehr lästig, sondern auch eine einheitliche Benennung ist schwer.

### Lösung / Feature

Ein Programm, dass Benennungsschemas nach Wachtypen, und mehrere Bennungstypen für Fahrzeuge (auch unterschiedliche bei zwei gleichen Fahrzeugen im Zug (GKWs/MzKws beim THW).
Grundsätzlich ziemlich ähnlich dem Skript "Rename-Manager" von DrTraxx.

### Sonstiges

[Ich kenne keine Umstände warum er nicht mehr im Forum aktiv sein darf und warum seine Skripte deaktiviert wurden, solltet ihr deshalb eine solche Idee schlecht finden der die Nennung nicht haben wollen, dann bin ich fein damit.]

**Comment by Cr4zyc4k3** [comment]
Siehe #26
