### ISSUE TITLE
[BUG]: Missing Italian translation/string

### ISSUE THREAD

**Issue by sup3r93** [LSS-Manager/LSSM-V.4#2329]
### What happened?

When opening the mission "Airport Tractor Fire" the inscriptions appear

> 1 modules.missionHelper.vehicles.captions.elw_airport
> 1 modules.MissionHelper.prerequisites.airport

![image](https://user-images.githubusercontent.com/94311785/236878080-6f65b659-c4a9-4212-a15a-4eb755a72105.png)

### How to reproduce?

1. Go to 'www.operatore112.it'
2. Wait a long time for it to spawn the right mission
3. When opening the mission "Airport Tractor Fire" the inscriptions appear

> 1 modules.missionHelper.vehicles.captions.elw_airport
> 1 modules.MissionHelper.prerequisites.airport

5. The error occurred

### Expected behavior

Correction of the Italian module

### System

- OS: Windows 11
- Browser and version: Microsoft Edge Version 113.0.1774.35 (Official Build) (64-bit)
- LSSM-Version: 4.7.4+20230426.1026 [stable]
- Game-Version: https://www.operatore112.it/

**Comment by Suchty112** [comment]
fixed in the beta branch :) https://github.com/LSS-Manager/LSSM-V.4/commit/7a02b62ce4eb08ac02c4e6cc1105addbf35d4f26
