### ISSUE TITLE
[Feature request]: Erweitere Gebäudeansicht: nicht gebaute Ausbauten anders darstellen

### ISSUE THREAD

**Issue by monstalein** [LSS-Manager/LSSM-V.4#2430]
### Is your feature related to a problem?

Wenn Ausbauten nicht aktiv sind und andere Ausbauten nicht gebaut sind, kann man dies in der Übersicht auf den ersten Blick nur schwer unterscheiden, da der Text in deutsch auch noch ähnlich lang ist.
Besser wäre, wenn "Nicht einsatzbereit" und "Noch nicht gebaut" unteschiedliche Farben hätten.

![2023-06-15 10_31_06-](https://github.com/LSS-Manager/LSSM-V.4/assets/3227357/5eb4585f-6b37-4f93-b303-6844048df7ad)

### Solution / Feature

Ausbauten die "Noch nicht gebaut" sind, in grau hinterlegen (bspw. class label-default)

![2023-06-15 10_35_59-](https://github.com/LSS-Manager/LSSM-V.4/assets/3227357/2b78c4f4-bded-4df8-936a-d243b3c90c78)

**Comment by Suchty112** [comment]
Wechsel mal bitte auf den branch 2431 in den einstellungen von der v4, wir haben das grau jetzt nicht genommen, da es sich ggfalls nicht abhebt vom lss dark mode, daher haben wir das primary-label genutzt.

**Comment by monstalein** [comment]
@Suchty112 mega gut :-) :-) Gefällt mir sehr :-) Vielen Dank
