### ISSUE TITLE
🌐🇩🇪[BUG]: [Benötigte Fahrzeuge verschönern] Feuerwehr-Leute-Zähler zählt GW-Lüfter nicht bei Anfahrt

### ISSUE THREAD

**Issue by monstalein** [LSS-Manager/LSSM-V.4#2493]
### What happened?

Wenn ein GW-Lüfter bei einem Einsatz ausgewählt wurde, werden die Feuerwehrleute nicht als benötigt gezählt. Auch wenn das Fahrzeug alamiert wurde, zählen die Leute nicht. Erst wenn das Fahrzeug am Einsatz-Ort ist, werden sie gezählt.

![Screenshot 2023-07-20 100751](https://github.com/LSS-Manager/LSSM-V.4/assets/3227357/a6cfe3d0-634d-423a-b429-d5f27d814101)

### How to reproduce?

1. Benötigt wird ein Einsatz, bei dem Feuerleute fehlen
2. Fahrzeug GW-Lüfter auswählen -> Zähler bei "Ausgewählt" ändert sich nicht
3. Das Fahrzeug alamieren
4. -> Zähler bei "Auf Anfahrt" bleibt unverändert

### Expected behavior

Die Zähler sollen das richtig zählen.

### System

- OS: Windows 11
- Browser and version: Firefox 115.0.2
- LSSM-Version: 4.7.7+20230715.0856 [stable]
- Game-Version: leitstellenspiel.de
-

**Comment by Cr4zyc4k3** [comment]
Das ist in der Tat komisch, denn das Personal ist korrekt hinterlegt. @jxn-30 irgendeine Idee was da schief läuft? Imo sieht das emv und auch die API sauber aus.
@monstalein Ist der Fehler reproduzierbar, sprich Strg+Shift+R  bzw. Strg+F5 und der Fehler tritt danach noch auf?

**Comment by Suchty112** [comment]
Sollte in den nächsten 10-15 Minuten dann auf dem Beta-Branch gefixxt sein :) Manchmal übersieht man bei neuen ContentPacks etwas :) . Danke für den Hint

**Comment by monstalein** [comment]
Funktioniert im beta Branch - vielen Dank euch :-)
