### ISSUE TITLE
[BUG]: [Benötigte Fahrzeuge verschönern] "Noch benötigt"-Zähler bei Feuerwehr-Leuten zählt beim Auswählen nicht mit

### ISSUE THREAD

**Issue by monstalein** [LSS-Manager/LSSM-V.4#2494]
### What happened?

Wenn man bei einem Einsatz eine gewisse Anzahl Feuerwehrleute benötigt, zählt der "Noch benötigt"-Zähler beim Fahrzeuge-Auswählen nicht mit.
Deshalb wird der Kasten oben auch nicht grün, wenn man genug Leute ausgewählt hat.
Nach der Alarmierung passt wieder alles.

Beim Auswählen:
![Screenshot 2023-07-20 114536](https://github.com/LSS-Manager/LSSM-V.4/assets/3227357/6880c246-66ca-40f4-a232-cd9b8444cf71)

Nach Alarmierung:
![Screenshot 2023-07-20 114832](https://github.com/LSS-Manager/LSSM-V.4/assets/3227357/ccc9a9ef-de52-4b3d-a011-715c50ec9b39)

### How to reproduce?

1. Einen Einsatz mit mind. Anzahl an Feuerwehrleuten wählen (bpsw. Brand im Holzpolter)
2. Zu wenige Leute schicken
3. Mehr Feuerwehr-Fahrzeuge auswählen -> "Noch benötigt" bleibt unverändert, erst wenn die Fahrzeuge alamiert wurden, passt die Zahl wieder

### Expected behavior

Der "Noch benötigt"-Zähler zählt mit, die entsprechende Zeile wird grün bei Erreichung der mind. Menge und der Kasten wird dann auch grün.

### System

- OS: Windows 11
- Browser and version: Firefox 115.0.2
- LSSM-Version: 4.7.7+20230720.1051 [beta]
- Game-Version: leitstellenspiel.de

### Additional

Danke euch für das tolle Tool, da macht das Spiel viel mehr Spass :-)

**Comment by Cr4zyc4k3** [comment]
Das ist kein Bug. Die Anzahl der Personen in den Fahrzeugen wird immer erst dann entgültig gesetzt wenn die Fahrzeuge alarmiert werden. Deshalb wird immer mit der Mindestanzahl an Personen gerechnet, weshalb - vor allem beip
personalstarken Fahrzeugen (HLF, MTF, etc.) die Anzahl bis zur Alarmierung deutlich unter der geforderten liegt.

**Comment by jxn-30** [comment]
Der "Noch benötigt" veändert sich doch nie schon beim Auswählen, oder? :thinking: 

Ich denke, das Problem ist folgendes: Die Mindestpersonalzahl der ausgewählten Fahrzeuge ist noch kleiner als die benötigte Personalzahl.

Man kann in den Einstellungen wählen, ob die Zeile grün wird, wenn die kleinere oder die größeren der beiden Zahlen die "benötigt"-Menge überschritten hat:
![grafik](https://github.com/LSS-Manager/LSSM-V.4/assets/27238105/8b650e31-57d9-4da6-bf86-3bf0972e206a)

Vor dem Ausrücken ist es nicht ohne erheblichen Aufwand möglich, die Personalzahl auf den Fahrzeugen zu berechnen, deshlab geben wir hier immer die Mindestzahl (=> wie viel Personal die ausgewählten Fahrzeuge zum Ausrücken benötigen) und die Maximalzahl (=> wie viel Personal die ausgewählten Fahrzeuge zusammen mitnehmen können, wenn das Personal vorhanden ist) an.

**Comment by Cr4zyc4k3** [comment]
Doch, tut es. Wenn du alle Anforderungen erfüllst wird der Kasten schon grün bevor alarmiert wurde
![grafik](https://github.com/LSS-Manager/LSSM-V.4/assets/69073372/c6e44a29-f8a9-4b47-a5ab-7dc416b956a0)

**Comment by monstalein** [comment]
@jxn-30 vielen Dank, der Schalter bringt die Lösung, beim Auswählen geht es auf grün, wenn die Option aktiv ist :-)

Ich sollte mehr schauen, was man alles einstellen kann - aber es ist halt auch so viel, was möglich ist :-)

Danke euch für das schnelle Feedback :-)
