### ISSUE TITLE
[Feature request]: Fahzeuge nach Anforderung Sortieren

### ISSUE THREAD

**Issue by BubbleUncle** [LSS-Manager/LSSM-V.4#2557]
### Is your feature related to a problem?

Gbt es eine Möglichkeit die benötigten Fahrzeuge von einem Einsatz nach Anforderung zu sortieren? Das die Fahrzeuge die benötigt werden als erstes in der Liste der Freienfahrzeuge angezeigt werden?

### Solution / Feature

Gbt es eine Möglichkeit die benötigten Fahrzeuge von einem Einsatz nach Anforderung zu sortieren? Das die Fahrzeuge die benötigt werden als erstes in der Liste der Freienfahrzeuge angezeigt werden?

**Comment by Cr4zyc4k3** [comment]
Meiner Meinung nach aufgrund der Komplexität der möglichen Fahrzeuganforderungen nicht ohne weiteres möglich. Auch sehe ich keinen Mehrwert gegenüber einer AAO.

**Comment by Cr4zyc4k3** [comment]
https://xyrality.helpshift.com/hc/de/23-mission-chief/faq/1521-what-are-alarm-and-response-regulations/

**Comment by BubbleUncle** [comment]
Thanks, I'll check it out!

Mike ***@***.***> schrieb am Do., 24. Aug. 2023, 20:16:
