### ISSUE TITLE
[Feature request]: Sort missions - Additional sort option

### ISSUE THREAD

**Issue by bagman002** [LSS-Manager/LSSM-V.4#2562]
### Is your feature related to a problem?

No

### Solution / Feature

I request that we add further functiallailty to the sort missions.

I would like to see the abiliity to sort by mission colour (Green, Red & Yellow) so that way its easier to filter the red missions as requiring action or additional resources.

**Comment by jxn-30** [comment]
Thanks for your suggestion :)

I will close here, as it is already written down in #11 .
