### ISSUE TITLE
[BUG]: Erweitertes Alarmfenster Verschönerte Ansicht Anzeigeprobleme

### ISSUE THREAD

**Issue by Dave2526** [LSS-Manager/LSSM-V.4#2762]
### What happened?

Seit kurzer Zeit wird die Verschönerte Ansicht im Alarmierungsfenster nur teilweise durch die Tabelle ersetzt,siehe Bild. Muss man da eventuell irgendwie Updates installieren?

### Wie kann man den Fehler reproduzieren?

In fast jedem Alarm Fenster

### Erwartetes Verhalten

Vor ca. 2 Wochen waren alle Daten in der Tabelle

### System

- Betriebssystem: Windows 10
- Browser und version: Firefox 120.0.1
- LSSM-Version: 4.7.10+20231129.1440 [stable]
- Spiel-Version: z.B. leitstellenspiel.de

### Sonstiges

![grafik](https://github.com/LSS-Manager/LSSM-V.4/assets/36053025/781767e2-bccf-431a-b91b-bb05f8cad2bd)

**Comment by jxn-30** [comment]
Danke, für die Meldung. Auf Beta sollte alles noch funktionieren, wir werden aber auch demnächst einen Release mit neuer Version veröffentlichen, wo das dann behoben sein sollte.

**Comment by jxn-30** [comment]
Ah, Fehler gefunden: Es war zu erwarten, dass es dazu kommt und wir haben deshalb präventiv letzte Woche schon einen passenden Commit gemacht und gepusht: https://github.com/LSS-Manager/LSSM-V.4/commit/d52d4ca1cc7b0017c56d894688c54e5b94464488
Leider haben wir vergessen, das ganze auch auf stable zu packen (auch wenn ich es extra angekündigt hatte…). Naja, auf stable ist es jetzt schon gefixed (Ab Version `4.7.10+20231205.1953`), aber den Release gibt es trotzdem demnächst :wink:
