### ISSUE TITLE
[Feature request]: Add building type in settings (Operatore112.it)

### ISSUE THREAD

**Issue by sup3r93** [LSS-Manager/LSSM-V.4#2791]
### Is your feature related to a problem?

Missing some buildings in the settings -> "List of customizable buildings" section

### Solution / Feature

In the "Building list filter" found on "Settings -> List of customizable buildings" for operatore112.it you need to add "Local Police Office" and "Civil Protection Headquarters"

**Comment by jxn-30** [comment]
@Suchty112 , you got time for that maybe?

otherwise, you could try using our guide to add the information yourself @sup3r93 . That would help us a lot! https://docs.lss-manager.de/en_US/contributing.html

**Comment by sup3r93** [comment]
> @Suchty112 , you got time for that maybe?
> 
> otherwise, you could try using our guide to add the information yourself @sup3r93 . That would help us a lot! https://docs.lss-manager.de/en_US/contributing.html

Sure I can do it

**Comment by sup3r93** [comment]
> @Suchty112 , you got time for that maybe?
> 
> otherwise, you could try using our guide to add the information yourself @sup3r93 . That would help us a lot! https://docs.lss-manager.de/en_US/contributing.html

https://github.com/LSS-Manager/LSSM-V.4/pull/2794

I tried to make the changes, and I hope I didn't make any mistakes
