### ISSUE TITLE
HAMMER!!!

### ISSUE THREAD

**Issue by buLLzAT** [LSS-Manager/LSSM-V.4#281]
Hey :) buLLzAT/Jan vom Discord hier.

Hab extra für euch diesen Account erstellt um euch zu Danken!
Hab v4 jetzt durchgetestet auf meinem Laptop und dank euch läuft LSS viel flüssiger.

Macht weiter so! 👍 

LG

**Comment by jxn-30** [comment]
Vielen Dank!

Um ordnung zu halten schließe ich hier :wink:
