### ISSUE TITLE
[BUG]: Telemetrie läuft nicht mehr

### ISSUE THREAD

**Issue by Tsumiki-Chan** [LSS-Manager/LSSM-V.4#284]
Seit den Änderungen, die die Telemetrieeinstellung in die Globalen Einstellungen packt läuft die telemetrie nicht mehr.

Es wird nicht versucht eine Telemetrie-Anfrage zu senden und auch das Löschen des IndexedDB-Keys bringt die Meldung nicht zurück (Modul wird garnicht geladen?)

**Comment by jxn-30** [comment]
Fixed!
