### ISSUE TITLE
[BUG]: Anfahrt von ELW2-Drohne wird bei Anzeige fehlender Fahrzeuge nicht als ELW1 erkannt.

### ISSUE THREAD

**Issue by chrlembeck** [LSS-Manager/LSSM-V.4#2853]
### What happened?

Geht man in einen Einsatz, in dem ein oder mehrere ELW1 benötigt werden und sendet dort ein paar benötigte Fahrzeuge und zusätzlich einen ELW2-Drohne, dann werden die benötigten und geschickten Fahrzeuge als anfahrende Fahrzeuge aufgelistet (wenn es genug sind, wir die Zeile auch grün). Sendet man allerdings einen ELW2-Drohne, welcher ja auch als normaler ELW2 und als ELW1 funktioniert, wird dieser nicht als anfahrender ELW1 erkannt und somit auch nicht angezeigt oder grün markiert.

### Wie kann man den Fehler reproduzieren?

Siehe Beschreibung oben

### Erwartetes Verhalten

Ein ELW2-Drohne sollte auch als ELW2 und als ELW1 erkannt werden.

### System

- Leitstellenspiel.de
- LSSM 4.7.12+20240128.2137 [stable]
- Chrome
- Windows 11

**Comment by jxn-30** [comment]
Danke für die Meldung 😊
Das ganze ist nun auf **Beta** gefixed und wird mit dem nächsten Relase dann auch auf stable online gehen.

**Comment by chrlembeck** [comment]
Wow, das ging ja fix. Danke!
