### ISSUE TITLE
Auto generated content in docs

### ISSUE THREAD

**Issue by N0W0RK** [LSS-Manager/LSSM-V.4#2940]
Is there any way to avoid the autogenerated content in the docs? It leads to massive changes when building locally where just the link targets are replaced.

As those changes are reverted during deployment, they just clutter up the working tree. 

A possible solution could be to generate a template for the footer upon build and then insert it when upon building.

**Comment by jxn-30** [comment]
I will keep that in mind for #2884 .
The docs system is very hacky and confusing atm so I don't think it is a good idea to hack in there even more before doing a rewrite of it.

**Comment by N0W0RK** [comment]
Is there any way to meaningfully contribute to the switch?

**Comment by jxn-30** [comment]
As I didn't start the switch yet, any contributions are welcome, as long as it works, is maintainable and maybe even eases contributing to docs from a translators perspective.
