### ISSUE TITLE
[BUG]: Tow Truck Missions not showing Crashed Cars

### ISSUE THREAD

**Issue by Tstory41** [LSS-Manager/LSSM-V.4#2974]
### What happened?

In the Extended Missionlist, it doesn't pull that missions need Crashed Cars.

### How to reproduce?

Go to any mission that requires a Tow Truck or says "Needs 1 Crashed Car" and it will not show up in the yellow box.

### Expected behavior

I expect it to list that it needs a Crashed Car or Tow Truck

### System

- OS: [e.g. Windows 10]
- Browser and version: [e.g. Firefox 101.3]
- LSSM-Version: [e.g. 4.6.1+20220917.1751 [stable]]
- Game-Version: [e.g. missionchief.co.uk]

**Comment by Cr4zyc4k3** [comment]
We're working on it. See https://github.com/LSS-Manager/LSSM-V.4/commit/6be2e797d3c969d685c71913534c4d45e0e1cb9f

**Comment by Suchty112** [comment]
fixed on beta (stable coming soon). if you want to remove the crashed car text in other missions, deactivate Crashed car (Title) in the settings. :)
