### ISSUE TITLE
[BUG]: Portuguese server domain is not up to date

### ISSUE THREAD

**Issue by mrxxix** [LSS-Manager/LSSM-V.4#2975]
### What happened?

[operador112.com/](https://www.operador112.com/) is the new Portuguese server domain. Had to manually change, and some other features are buggy or out of place, or simply don't work. 

### How to reproduce?

Both of the domains are available and it's the same server.

### Expected behavior

What would be expected is the new domain to be added so it can launch with it.

### System

- LSSM-Version: 4.7.12+20240321.2220 [stable]
- Game-Version: operador112.com

**Comment by mrxxix** [comment]
`// ==UserScript==
// @name         LSS-Manager V.4
// @version      4.7.12-CZ-DK-DE-AU-GB-US-ES-MX-FI-FR-IT-JP-KR-NO-NL-PL-BR-PT-RO-RU-SK-SE-TR-UA
// @author       The LSSM-Team: Sanni, Jan (jxn_30), Ron31, Crazycake
// @description  LSSM V4 is a Script-Collection for Leitstellenspiel, Missionchief, Meldkamerspel and its other language versions.
// @namespace    https://lss-manager.de/
// @homepage     https://docs.lss-manager.de/
// @downloadURL  https://v4.lss-manager.de/lssm-v4.user.js
// @updateURL    https://v4.lss-manager.de/lssm-v4.user.js
// @supportURL   https://docs.lss-manager.de/en_US/error_report
// @icon         https://docs.lss-manager.de/img/lssm.png
// @match        https://www.operacni-stredisko.cz/*
// @match        https://policie.operacni-stredisko.cz/*
// @match        https://www.alarmcentral-spil.dk/*
// @match        https://politi.alarmcentral-spil.dk/*
// @match        https://www.leitstellenspiel.de/*
// @match        https://polizei.leitstellenspiel.de/*
// @match        https://www.missionchief-australia.com/*
// @match        https://police.missionchief-australia.com/*
// @match        https://www.missionchief.co.uk/*
// @match        https://police.missionchief.co.uk/*
// @match        https://www.missionchief.com/*
// @match        https://police.missionchief.com/*
// @match        https://www.centro-de-mando.es/*
// @match        https://www.centro-de-mando.mx/*
// @match        https://www.hatakeskuspeli.com/*
// @match        https://poliisi.hatakeskuspeli.com/*
// @match        https://www.operateur112.fr/*
// @match        https://police.operateur112.fr/*
// @match        https://www.operatore112.it/*
// @match        https://polizia.operatore112.it/*
// @match        https://www.missionchief-japan.com/*
// @match        https://www.missionchief-korea.com/*
// @match        https://www.nodsentralspillet.com/*
// @match        https://politiet.nodsentralspillet.com/*
// @match        https://www.meldkamerspel.com/*
// @match        https://politie.meldkamerspel.com/*
// @match        https://www.operatorratunkowy.pl/*
// @match        https://policja.operatorratunkowy.pl/*
// @match        https://www.operador193.com/*
// @match        https://www.jogo-operador112.com/*
// @match        https://www.operador112.com/*
// @match        https://policia.jogo-operador112.com/*
// @match        https://www.jocdispecerat112.com/*
// @match        https://www.dispetcher112.ru/*
// @match        https://www.dispecerske-centrum.com/*
// @match        https://www.larmcentralen-spelet.se/*
// @match        https://polis.larmcentralen-spelet.se/*
// @match        https://www.112-merkez.com/*
// @match        https://www.dyspetcher101-game.com/*
// @run-at       document-idle
// @grant        GM_info
// @grant        unsafeWindow
// ==/UserScript==
/* global I18n, user_id */
const e=()=>{const e=document.createElement("script");e.src=`https://v4.lss-manager.de/core.js?_=${Math.floor(Date.now()/6e5)}&branch=${localStorage.getItem("lssmv4_branch")??"stable"}`;e.setAttribute("type","module");e.setAttribute("async","");unsafeWindow["lssmv4-GM_Info"]=JSON.parse(JSON.stringify(GM_info));document.body.append(e)};if((!window.frameElement||window.frameElement?.src.startsWith("https"))&&!/^\/users\//u.test(window.location.pathname)&&"undefined"!=typeof user_id&&"undefined"!=typeof I18n)if(window!==window.parent&&window.parent.hasOwnProperty("lssmv4-redesign-lightbox")){const t="lssmv4-redesign-iframe-trigger-lssm-load";window.parent.addEventListener(t,e);window.addEventListener("pagehide",(()=>window.parent.removeEventListener(t,e)));window.parent["lssmv4-redesign-lightbox"].src=new URL(window.location.href).toString()}else e();
`

This fixed it. Just added the new domain on Tampermonkey editor.

**Comment by Suchty112** [comment]
> ### What happened?
> [operador112.com/](https://www.operador112.com/) is the new Portuguese server domain. Had to manually change, and some other features are buggy or out of place, or simply don't work.

That is wrong. The official domain of PT is https://www.jogo-operador112.com/ . It is linked on Facebook and in the other countries at the bottom of the flags.

Unfortunately, with the current state of our script, we can only support one country domain. And that is the official https://www.jogo-operador112.com/ domain

**Comment by kdev** [comment]
@Suchty112 how do we proceed with this? As far as my understanding goes we can only support 1 domain per game (@jxn-30)

**Comment by jxn-30** [comment]
technically, it probably only requires an extra field in config (smth. like string[] additionalUrls) plus adjustment in userscript generation to include this URL(s) too.
As far as I know we don't rely on the exact domain anywhere within LSSM itself but I cannot guarantee this atm. Accessing via the correct game URL (jogo-operando) is still the recommended way!

**Comment by kdev** [comment]
Since we support the correct game url and haven't had any complains from other users, I think we can close this as "works-as-intended".

**Comment by jxn-30** [comment]
According to the devs, any other domain than `jogo-operador112.com` should forward to `jogo-operador112.com`. They will ensure that this will happen again.
This confirms us in our current approach not to include multiple domains for a single game.

**Comment by Cr4zyc4k3** [comment]
Open till the redirects are implemented.

**Comment by kdev** [comment]
> Open till the redirects are implemented.

Again, this is not an issue on our end so it does not belong here as an open issue. I will close this.

**Comment by Cr4zyc4k3** [comment]
Fixed by the game devs. Every domain should now redirect to jogo-operator112
