### ISSUE TITLE
[BUG]: "Benötigte Fahrzeuge verschönern": THW-Einsatzekräfte werden ignoriert

### ISSUE THREAD

**Issue by monstalein** [LSS-Manager/LSSM-V.4#3024]
### What happened?

Beim Einsatz wird das benötigte THW-Personal nicht im verschönerten Kasten angezeigt (siehe Screenshots):

![Screenshot 2024-05-13 115337](https://github.com/LSS-Manager/LSSM-V.4/assets/3227357/0b648ead-7109-4df3-8477-36a9bdfac40d)

![Screenshot 2024-05-13 115346](https://github.com/LSS-Manager/LSSM-V.4/assets/3227357/4e6af6d5-c5fc-456c-8e53-ec2ede710d26)

### Wie kann man den Fehler reproduzieren?

1. Alarm-Fenster von Einsatz öffnen, wo THW-Personal gebraucht wird (evtl. PERSONENSUCHE IM WALD)
2. warten bis LSSM-Script geladen
4. Das Fehlverhalten tritt auf

### Erwartetes Verhalten

Die THW-Einsatzkräfte werden auch in dem verschönerten Kasten dargestellt

### System

- Betriebssystem: Windows 11
- Browser und version: Edge 124.0.2478.8
- LSSM-Version: beta (4.7.12+20240512.1311)
- Spiel-Version: leitstellenspiel.de

**Comment by Cr4zyc4k3** [comment]
Hui, da ist uns tatsächlich was durchgerutscht. Kannst du mir sagen, was der Singular ist? Sprich wenn nur noch eine Einsatzkraft fehlt?

**Comment by Cr4zyc4k3** [comment]
Sollte mit #3025 gefixt sein. Sobald der build durch ist gerne ausprobieren. Dazu in den Einstellungen einfach "Version wählen" auf  "fix/emvTHW" auswählen.

**Comment by monstalein** [comment]
Funktioniert super - vielen Dank :-)

**Comment by jxn-30** [comment]
Ist mittlerweile auch auf beta gelandet, der Preview-Branch wird in 7 Tagen automatisch gelöscht werden.

**Comment by monstalein** [comment]
Der Fehler ist leider wieder da. Eingesetzte Version: stable (4.7.12+20240527.1600) in Firefox 126.0.1 unter Windows 11

**Comment by Suchty112** [comment]
Ist jetzt auch auf dem Stable. Have fun.
