### ISSUE TITLE
🇳🇱[mh]: oneof_fire_engine_or_rescue not translated

### ISSUE THREAD

**Issue by DigiLive** [LSS-Manager/LSSM-V.4#3119]
### What happened?

The mission helper literary lists `modules.mission Helper.vehicles.captions.oneof_fire_engine_or_rescue` as a vehicle.

`oneof_fire_engine_or_rescue` is not present in file `src/modules/missionHelper/i18n/nl_NL.json`

Language: Dutch.
Mission: https://politie.meldkamerspel.com/einsaetze/1007

### How to reproduce?

1. Open a mission.
2. Notice the untranslated vehicle.

### Expected behavior

It's expected to see all vehicles translated

### System

- OS: Windows 10
- Browser and version: Firefox 101.3
- LSSM-Version: 4.7.12+20240618.1316 [stable]
- Game-Version: politie.meldkamerspel.com

### Additional

![afbeelding](https://github.com/user-attachments/assets/f1758ab5-6f56-4fa1-ba3f-c6ef1bf35a98)

**Comment by Piet2001** [comment]
Yes i a change that was preformed yesterday. 
2 new keys have been made in the game. 
`need_oneof_fire_engine_or_rescue`
`need_oneof_wildfire_engine_or_airport_fire_engine`

**Comment by Piet2001** [comment]
@DigiLive see commit for how it can be fixt. You can always try youself when there is a new translation missing. The magic of opensource.

**Comment by Suchty112** [comment]
Fixed on the Beta Branch :)
