### ISSUE TITLE
[BUG]: buildingListFilter not working on CZ version

### ISSUE THREAD

**Issue by Tadjinton** [LSS-Manager/LSSM-V.4#3124]
### What happened?

* After enabling buildingListFilter in the AppStore.
* It looks like the module won't load.
* Changes in the building list do not appear.
* The tab for the buildingListFilter module is missing in the LSSM settings.

In Google Chrome -> Developer Tools -> Console, it displays the following error message:
```
Uncaught (in promise) TypeError: Cannot convert undefined or null to object webpack://lss-manager-v4/src/modules/buildingListFilter/settings.ts:11
    at Function.values (<anonymous>)
    at eval (settings.ts:11:27)
    at Array.map (<anonymous>)
    at __WEBPACK_DEFAULT_EXPORT__ (settings.ts:8:57)
    at eval (registerModuleSettings.ts:6:38)
    at async eval (loadAndExecuteModule.ts:21:9)
```
```
![lssm_buildingListFilter](https://github.com/user-attachments/assets/3cfc7f19-5cf6-4bdb-9f3d-c6bd946e3341)
```

### How to reproduce?

1. Open AppStore
2. Enable module buildingListFilter

### Expected behavior

I assume that after enabling the buildingListFilter module, the LSSM UI for filtering buildings should be displayed.

### System

- OS: Windows 10
- Browser and version: Google Chrome 126.0.6478.185
- LSSM-Version: 4.7.12+20240725.0658 [beta]
- Game-Version: https://www.operacni-stredisko.cz/

**Comment by jxn-30** [comment]
Should probably no be fixed on beta as #3125 added the translations.
First beta release including this change is `4.7.12+20240726.1436`.
