### ISSUE TITLE
[Feature Request]: Benötigte Fahrzeuge verschönern

### ISSUE THREAD

**Issue by minerop5000** [LSS-Manager/LSSM-V.4#315]
**Geht deine Idee aus einer Problemstellung hervor?**
Im modul erweitertes Alarmfenster in "Benötigte Fahrzeuge verschönern" ist die zweigeteile tabelle recht unübersichtlich. und man muss immer hin und her scrollen um die tabelle zu sehen und seine fahrzeuge zu alarmieren

**Lösung / Feature**
Im modul erweitertes Alarmfenster in "Benötigte Fahrzeuge verschönern" hätte ich gerne, dass die tabelle nur auf der rechten Hälfte angezeigt wird und vorallem nur "eine tabelle" und nicht in zwei aufgeteilt

**Sonstiges**
ist das der richtige weg vorschläge zu vorhandenen modulen zu machen? habe keinen anderen weg gefunden.

Bilder:
also schön wäre sowas:
![grafik](https://user-images.githubusercontent.com/75438446/101167069-a38e9b80-3639-11eb-80b0-e62e5679180e.png)

anstelle:
![grafik](https://user-images.githubusercontent.com/75438446/101167113-b6a16b80-3639-11eb-9081-08d5be793ffb.png)

**Comment by jxn-30** [comment]
> **Sonstiges**
> ist das der richtige weg vorschläge zu vorhandenen modulen zu machen? habe keinen anderen weg gefunden.
Ja. Sehr vorbildich!

Zu deiner Idee: klick mal auf dieses Zeichen wo zwei `^` übereinander sind. Dann legt sich das in ein Overlay und wird auf eine Tabelle zusammengeschoben. Du kannst das Fenster im Overlay-Modus auch verschieben :)

**Comment by minerop5000** [comment]
> 
> 
> > **Sonstiges**
> > ist das der richtige weg vorschläge zu vorhandenen modulen zu machen? habe keinen anderen weg gefunden.
> > Ja. Sehr vorbildich!
> 
> Zu deiner Idee: klick mal auf dieses Zeichen wo zwei `^` übereinander sind. Dann legt sich das in ein Overlay und wird auf eine Tabelle zusammengeschoben. Du kannst das Fenster im Overlay-Modus auch verschieben :)
> 
> Wäre das so etwas, was du dir wünscht?

ja die zusammengeschobene tabelle ist schon gut, aber ich hätte die gerne wie den einsatzhelfer eingebettet in die seite

**Comment by jxn-30** [comment]
Alles klar. Wäre als Position direkt über dem Einsatzhelfer in Ordnung?

**Comment by minerop5000** [comment]
> 
> 
> Alles klar. Wäre als Position direkt über dem Einsatzhelfer in Ordnung?

jop

**Comment by jxn-30** [comment]
Ist notiert. Mal schauen, wann ich dazu komm :)

**Comment by jxn-30** [comment]
Sodele, für die Betas is das dann online. Sobald Version **4.1.7** veröffentlicht wird, werd ich hier schließen, weil es dann für alle online ist :)

**Comment by jxn-30** [comment]
Mit #352 erledigt!
