### ISSUE TITLE
[BUG]: [general extensions new building] throw too many alerts

### ISSUE THREAD

**Issue by Cr4zyc4k3** [LSS-Manager/LSSM-V.4#332]
**Describe what happens**
If you enable the module general extensions with the option "remember building type" or "remember control center" and try to build a new building without a name it will throw modals "please select new building" on every click at "build for x Credits". If only 1 option is enabled it will overwrite the ingame message that you need to select a name for this building.

If you enable both options and try to build one the formula will show you the ingame message "to short (min. 2 chars.)" and sometimes it removes the "build for x Credits/Coins"-button. They will appear after you select a new building-type. 

**How to reproduce?**
1. Enable the module "general extensions"
2. Enable the option "remember control center" xor "remember building type"
3. Try to build an new building
4. The error occured

**Expected behavior**
Show the right error message and checking whether an div with the id="building_new_info_message" exists and prevent from building another one

**Screenshots**
![grafik](https://user-images.githubusercontent.com/69073372/101329992-62cd9700-3872-11eb-868c-05b0c8fc9e59.png)
(Just in window design for better viability. Also buggy in normal mode).

**Further notes: *(please complete)***
 - OS: Win 10pro
 - Browser: FF 83.0 (64Bit)
 - LSSM-Version: 4.1.6+20201206.2143 [beta] 
 - for Smartphones / Tablets: your device: -
 - which of the games are you playing: .de
 - your ingame name: Crazycake (264361)

**Comment by jxn-30** [comment]
@Cr4zyc4k3 i added a form validation with **Beta Build 4.1.6+20201208.1214** Please check if that issue is fixed :)

**Comment by Cr4zyc4k3** [comment]
Wörks perfect
