### ISSUE TITLE
[BUG]: Incorrect use of <label for=FORM_ELEMENT>

### ISSUE THREAD

**Issue by ThunderLe0** [LSS-Manager/LSSM-V.4#3322]
### What happened?

Nach dem öffnen einer Mission im selben Tab erscheint im Entwicklerfenster die **Medung Incorrect use of <label for=FORM_ELEMENT>** .
Als Beschreibung wird folgendes angegeben:

_The label's for attribute doesn't match any element id. This might prevent the browser from correctly autofilling the form and accessibility tools from working correctly.
To fix this issue, make sure the label's for attribute references the correct id of a form field._

Öffne ich das Fenster in einem Neuen Tab erscheinen diese Meldungen nicht.

### Wie kann man den Fehler reproduzieren?

siehe oben

### Erwartetes Verhalten

keine Meldung

### System

- Betriebssystem: Windows 11
- Browser und version: Chrome Version 131.0.6778.86 (Offizieller Build) (64-Bit)
- LSSM-Version: 4.7.12+20241023.2121 [stable]
- Spiel-Version: leitstellenspiel.de
- Fenster Design Dunkel

### Sonstiges

Augenscheinlich hat es erstmal keine Auswirkungen.

**Comment by jxn-30** [comment]
Hast du einmal bitte einen Screenshot der Meldung? Alternativ nochmal den ganzen Text. Da scheint brim Kopieren die wichtige Information, bei welchem Element das passiert verloren gegangen :)

**Comment by ThunderLe0** [comment]
Hi, ups...
klar hier als Screenshot.
![LSS](https://github.com/user-attachments/assets/decdfafc-3bcb-4f75-91cb-1bd394e4bc40)

**Comment by jxn-30** [comment]
Ja okay wow, daraus wird man nicht wirklich schlauer leider. Sieht so aus, als müsste man auf jedes einzelne "Knoten mit Richtlinienverletzung" klicken, um zum jeweiligen Knoten zu gelangen :woozy_face: _Man könnte ja meinen, es könnte schlau sein, wenigstens einen Hinweis auf den Knoten schon mit anzuzeigen..._

Ich weiß, das ist jetzt ein bisschen Arbeit, aber kannst du evtl. auf die Links "Knoten mit Richtlinienverletzung" klicken und wenn da dann was kommt, wo irgendwie sinnvoll / hinweisgebend ausschaut davon auch einen Screenshot machen? :sweat_smile:

**Comment by Cr4zyc4k3** [comment]
> Hi, ups... klar hier als Screenshot. ![LSS](https://private-user-images.githubusercontent.com/95706206/390865823-decdfafc-3bcb-4f75-91cb-1bd394e4bc40.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4MTQyMzUsIm5iZiI6MTczMjgxMzkzNSwicGF0aCI6Ii85NTcwNjIwNi8zOTA4NjU4MjMtZGVjZGZhZmMtM2JjYi00Zjc1LTkxY2ItMWJkMzk0ZTRiYzQwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDE3MTIxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0N2U3MWQ1NGZlYmM4NWQyMDMxYzIxNDQ2ZTBiY2RhMWNmOGM5YTg3NjJiNzUxYzVjYzljYWFiMjFiMzZiMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.189hBhSTqWx5Oe5inXGpIMJUCZQH-uAFx0NHs9qkVVw)

Hat Chrome seine dev-Console ein Rebranding verpasst? Sieht irgendwie so gar nicht nach Chrome aus. (Hab den aber fairerweise seit Jahren  nicht mehr offen gehabt)

**Comment by ThunderLe0** [comment]
@Cr4zyc4k3 Ja ist Chrome, ich kenn nur diese Darstellung ;-)

@jxn-30 
Alle knoten verweisen auf ein nahezu gleiches Label.
Es scheint etwas mit den Abrollbehältern zutun zu haben. (Ich momentan genau 11)
![LSS-2](https://github.com/user-attachments/assets/23c21100-3dee-46e7-a1e7-c64687e15720)

**Comment by kdev** [comment]
So wie ich das sehe, müsste das `for="<xx>"` mit der ID des Input Elements übereinstimmen. Damit sollte das dann aber auch getan sein?

**Comment by jxn-30** [comment]
Jup, wenn das Attribut die Fahrzeug-ID mit drin hätte, dann würde sich Chrome nicht beschweren.
Die Elemente kommen aber vom Spiel selbst. Ich geb das aber mal ans Spiel-Team weiter , dann können die das fixen :)
