### ISSUE TITLE
[BUG]: Personal ohne passende Ausbildung ausblenden in Verbindung mit GW-Höhenrettung

### ISSUE THREAD

**Issue by Patti2101** [LSS-Manager/LSSM-V.4#348]
**Verhalten beschreiben**
Wenn man in der erweiterten Gebäudeansicht Personal dem GW-Höhenrettung zuweisen möchte und dabei die Checkbox Personal ohne passende Ausbildung ausblenden angeklickt hat und sich das Personal noch im Höhenrettung Lehrgang befindet wird dieses nicht angezeigt. Bei den anderen Fahrzeugen die ich getestet habe hat das funktioniert obwohl der Lehrgang noch lief.

**Screenshots**
![Ausbildung](https://user-images.githubusercontent.com/35320639/101846779-f85a7680-3b51-11eb-950e-c4f83f537f18.png)
![Personal ohne passende Ausbildung](https://user-images.githubusercontent.com/35320639/101846793-fc869400-3b51-11eb-9a23-b88c1acc8a1b.png)

**Sonstige Hinweise:**
 - Betriebssystem: Win 10 Home
 - Browser: Firefox 83
 - LSSM-Version: 4.1.6
 - Welches der Spiele spielst du?: LSS.de
 - Dein Name im Spiel: DjPaTTi

**Comment by jxn-30** [comment]
Jup, kann ich codetechnisch bestätigen.

Note to myself: schooling statt shownSchooling?

**Comment by jxn-30** [comment]
So, für die Betas ist der Fix bereits online, für alle ist das ab **Version 4.1.7** (vermutlich noch heute) online. Sobald die neue Version released wird, schließe ich hier :)
