### ISSUE TITLE
[BUG]: delete-button on ingame-forum doesnt work

### ISSUE THREAD

**Issue by buLLzAT** [LSS-Manager/LSSM-V.4#367]
**Describe what happens**
Add a detailed description on how the bug looks like

When the delete-popup appears on screen its not possible to click the delete button on the right side.

**How to reproduce?**
Explain here what you did when the error occured

1. open the ingame-forum
2. click on a thread
3. hit the delete-button on a post
4. the delete-popup appears
5. try to press the delete-confirm button on the right side

**Expected behavior**
What did you expect LSS-Manager to do?

delete the forum-post
**Screenshots**
If possible, add screenshots here to visualize the bug
![image](https://user-images.githubusercontent.com/74836832/102504806-933adf80-4081-11eb-83bd-29d6d7072972.png)

[browser-console-log](https://pastebin.com/drAivQtE)

**Further notes: *(please complete)***
 - OS: Win 10 Pro Build 19042.685
 - Browser: Brave Beta Version 1.19.62 Chromium: 87.0.4280.101 (Offizieller Build) beta (64-Bit)
 - LSSM-Version: 4.1.7+20201211.1356 [stable] + v3 STABLE 3.3.7
 - which of the games are you playing: Leitstellenspiel.de
 - your ingame name: [Profile](https://www.leitstellenspiel.de/profile/223032)

**Further**
I already mentoined this bug in the discord-channel #lssm-help a few weeks ago. Now Its officially also on Git :)

Discord-Profile: 
buLLzAT/Jan#0122

**Comment by KokosnussDEV** [comment]
I think this is a known bug (@jxn-30?)

**Comment by Ron31** [comment]
Yes 😅

**Comment by buLLzAT** [comment]
was it wrong to open this issue?

**Comment by buLLzAT** [comment]
*push*

**Comment by Ron31** [comment]
Should be fix with commit [1cc7fce](https://github.com/LSS-Manager/LSSM-V.4/commit/1cc7fce8cca478bbc5a54a9e7011f79b45657ec1) and version `4.1.9+20210103.2206 [beta]`
