### ISSUE TITLE
[BUG]: [ecw] AAO-Counter dont work properly with ingame AAO reset 

### ISSUE THREAD

**Issue by Cr4zyc4k3** [LSS-Manager/LSSM-V.4#401]
After resetting AAO with a custom AAO (just select "Bisherige Auswahl im Alarmierungsfenster zurücksetzen") the first click wont be counted in the AAO-Counter and wont get a fancy border. It doesnt matter whether you reset with the "AAO-Zähler / -Umrandung zurücksetzen" button.

**How to reproduce?**
Explain here what you did when the error occured
for example:
1. build a "AAO-Reset" button
2. Go to a mission
3. Select until the the AAO is red
4. Reset with the your AAO-Reset
5. Select a AAO

**Expected behavior**
Usual stuff

**Screenshots **

https://user-images.githubusercontent.com/69073372/103525656-dff32880-4e7f-11eb-98c3-081ba8ff35cb.mp4

**Further notes: *(please complete)***
 - OS: Win 10 Pro 19041.685
 - Browser: FF 84.0.1 (64-Bit)
 - LSSM-Version: 4.1.9+20210104.0716 [beta] 
 - which of the games are you playing: .de
 - your ingame name: Crazycake (264361)

**Comment by jxn-30** [comment]
This happens in this case because the ARR is marked red.
ARR-Counter does not update when ARRs are not available :upside_down_face: 
=> Not a Bug but we may consider this as a new feature :see_no_evil: 

Will close here as already added to the List for features ;)
