### ISSUE TITLE
[Feature Request]: Dispatch-Center button on LSS/leitstellenansicht

### ISSUE THREAD

**Issue by TeraCineFan** [LSS-Manager/LSSM-V.4#411]
There are no dispatch-centers visible on https://www.leitstellenspiel.de/leitstellenansicht

**solution**
pls add a button to only show the owned dispatch centers 

like this: 
![Screenshot 2021-01-06 131513](https://user-images.githubusercontent.com/74836832/103767996-f507bd00-5021-11eb-9531-fe2ee93a3ad3.png)

**alternatives**
maybe add a sub-button to go directly to this building if you click on the dispatch-center-filter button
![Screenshot 2021-01-06 132131](https://user-images.githubusercontent.com/74836832/103768135-3f893980-5022-11eb-9eb5-5e12cd27c316.png)

Greetings [buLLzAT](https://github.com/buLLzAT)

**Comment by buLLzAT** [comment]
what about a filter button for only helicopter-stations only?

**Comment by Cr4zyc4k3** [comment]
Since today this is implemented by the game

**Comment by Cr4zyc4k3** [comment]
Done
