### ISSUE TITLE
[BUG] Extended alarm window: Temporary mission gone from interface, still in .lssm file

### ISSUE THREAD

**Issue by CrustaShrimp** [LSS-Manager/LSSM-V.4#414]
**Describe what happens**
In the Dutch version of the game, there are temporary mission types, usually seasonal (Christmas, New Years, Easter etc.)
After adding those mission types to the "Meldingstrefwoord" (part of the Extended alarm window), the correct labels show up.
However, the settings page in LSSM only allows mission types that are in the active JSON to be selected, the rest cannot be chosen.
Hence, after the mission types are deleted from the JSON, they cannot be seen in the settings anymore.
When you export the settings however, the mission types IDs are still there

**How to reproduce?**
Explain here what you did when the error occured
for example:
1. Add temporary misison to the Extended alarm window
2. Export the LSSM settings and verify the mission ID is stored in the correct label
3. Wait for the mission type to be deleted from the JSON, mission type is no longer available
4. Check the LSSM settings, note that the mission ID is gone from the list
5. Export the LSSM settings and see the mission ID still there

**Expected behavior**
Either remove the ID from the exported settings, or keep showing it in the online settings menu, with a placeholder name like "Mission not available"

**Screenshots**
Example: mission ID 169 has been removed from the JSON.
It does not show up in the online settings, but when exporting them, it is still in the LSSM file.

Online settings:
![image](https://user-images.githubusercontent.com/60628153/103947779-efe96180-5138-11eb-8775-5f44ea1e51c3.png)

Exported settings:
![image](https://user-images.githubusercontent.com/60628153/103947659-c0d2f000-5138-11eb-9716-04f48683afbf.png)

**Further notes: *(please complete)***
 - OS: W10
 - Browser: Chrome
 - LSSM-Version: 4.1.9+20201231.1843[stable]
 - which of the games are you playing: Meldkamerspel.nl [NL]
 - your ingame name: CrustaShrimp

**Further**
-

**Comment by JRH-1997** [comment]
@jxn-30 I think this one is solved by the update of the API?
