### ISSUE TITLE
[BUG]: Restliche Einsatzdauer in Einsatzübersicht funktioniert nicht mehr

### ISSUE THREAD

**Issue by thm27new** [LSS-Manager/LSSM-V.4#457]
**Verhalten beschreiben**
Seit dem letzten Update auf LSSM-Version 4.1.11+20210123.1852 [stable] ist die Anzeige der verbleibenden Einsatzzeit in der Einsatzübersicht verschwunden. Ich kann die Zeit nur sehen, wenn ich den jeweiligen Einsatz öffne.
Ich habe die Zeitanzeige in den Einstellungen schon deaktiviert ud neu aktiviert. Auch habe ich denn LSSM kurz komplett deaktiviert und wieder aktiviert. 
Und natürlich habe ich auch den Rechner neu gestartet. 
Das Problem besteht seit gestern. Im laufenden Betrieb war die Zeit plötzlich nicht mehr sichtbar. Kurz zuvor hat sich der LSSM geupdated. 

**Wie kann man den Fehler reproduzieren?**
Beschreibe hier, wenn möglich, was du gemacht hast, als der Fehler auftrat.
z.B.:
Fehler tritt bei mir permanent auf. Ich war im laufenden Spiel, als mir auffiel, dass die Zeit nicht mehr angezeigt wird. Ich kann dem keine eindeutige Handlung zuordnen.

**Erwartetes Verhalten**
Anzeige der restlichen Einsatzdauer direkt in der Einsatzübersicht

**Screenshots**
Wenn möglich, füge hier Screenshots ein, die uns helfen, den Fehler schneller zu beheben

**Sonstige Hinweise: *(bitte ergänzen)***
 - Betriebssystem: Windos 10 Home 64bit
 - Browser: Google Chrome (aktuellste Version)
 - LSSM-Version: 4.1.11+20210123.1852 [stable]
 - bei Smartphones / Tabletts: Gerät:
 - Welches der Spiele spielst du?: 
 - Dein Name im Spiel: thm27

**Sonstiges**
Füge hier sonstige Hinweise ein.

**Comment by jxn-30** [comment]
Das ist ja mal merkwürdig 🤔
Muss ich mir mal genauers anschauen.

**Comment by thm27new** [comment]
Moin,

konntest du das Problem nachstellen, bzw. hast du schon einen Ansatz, woran es liegen könnte?
Zur Info: ich habe zwischnzeitlich an meinem Desktop-PC mal probieren können. Auch da WIndows 10 Home und Chrome im Einsatz.
Das Problem besteht auf dem Rechner in gleicher Weise.
Vielleicht kann das die Ursache weiter eingrenzen. Ist schade, denn die Restdaueranzeige im Einsatzhelfer ist mir eins der liebsten Features.

**Comment by jxn-30** [comment]
Nein, leider bin ich noch nicht dazu gekommen, das ganze zu untersuchen.

**Comment by jxn-30** [comment]
No do gugsch no, manchmal ist es einfach nur ein Fragezeichen, dass das weite gesucht hat :see_no_evil: 
Wird mit dem nächsten stable-Update für alle behoben sein :see_no_evil:
