### ISSUE TITLE
[Feature Request]: Custom order missionhelper

### ISSUE THREAD

**Issue by kdev** [LSS-Manager/LSSM-V.4#464]
**Is your feature request related to a problem?**
I could write no and just leave this blank but I'm gonna try:
I was playing LSS and I was thinking about how to improve LSSM so I came up with an idea to enhance our beloved MissionHelper!

**Solution / Feature**
I would like to have a setting allowing me to customize the order of  how the vehicles needed are shown.

**Alternatives**
-- none --

**Additional**
-- none --

**Comment by KokosnussDEV** [comment]
bump

**Comment by orangeNKeks** [comment]
I would love this option

**Comment by jxn-30** [comment]
If anyone implements it, this will be achievable by feature `custom design template` of #25 
Gonna close here ;)
