### ISSUE TITLE
[Project] Ideas for Checks

### ISSUE THREAD

**Issue by KBOE2** [LSS-Manager/LSSM-V.4#54]
Checks for PRs are a good way to keep the Project clean.

Ideas:
* ESLint
* JSON-Files sorted
* `window.tellParent` code is transpiled enough (See #52)
* build succeeds (dev and stable)
* Code is ES6 or newer (difficult)

––– suggestions may be added at any time –––

**Comment by KokosnussDEV** [comment]
Isn't this fulfilled by TravisCI?

**Comment by KBOE2** [comment]
partly. But Travis is enough so far (when it commits and pushes automatically).
The
> `window.tellParent` code is transpiled enough (See #52)
is harder work to do, so I will not include that for now :wink: 

Will close here, thanks
