### ISSUE TITLE
[BUG]: Uptime des Server nicht erreichbar

### ISSUE THREAD

**Issue by Notme112** [LSS-Manager/LSSM-V.4#650]
**Verhalten beschreiben**
Nichts passiert, wenn man die Seite [Uptime - LSS Manager](https://status.lss-manager.de/) aufruft, es gibt seitens UptimeRobot einen 404 Fehler.

**Wie kann man den Fehler reproduzieren?**
Beschreibe hier, wenn möglich, was du gemacht hast, als der Fehler auftrat.
z.B.:
1. Rufe die Seite [LSS-Manager - Uptime](https://status.lss-manager.de/) auf.
2. Das Fehlverhalten tritt auf

**Erwartetes Verhalten**
Ich erwarte hier, die Uptime zu sehen

**Screenshots**
Sollte nicht nötig sein

**Sonstige Hinweise: *(bitte ergänzen)***
 - Betriebssystem: Windoof
 - Browser: Chrome
 - LSSM-Version: nicht wichtig
 - bei Smartphones / Tabletts: Gerät: //
 - Welches der Spiele spielst du?: LSS
 - Dein Name im Spiel: //

**Sonstiges**
//

**Comment by NiZi112** [comment]
### > - [ ] [`_**Dies ist ein Test**_`](www.wikipedia.de)

**Comment by kdev** [comment]
@jxn-30 I think we can close this as we now provide detailed uptime monitoring on our [Discord](https://discord.gg/RcTNjpB)

**Comment by jxn-30** [comment]
No, because the new Statuspages will be made public soon.

**Comment by jxn-30** [comment]
Is fixed since Serverumzug
