### ISSUE TITLE
[BUG]: Anpassbare Gebäudeliste: Kleinwachen werden nicht von normalen Wachen unterschieden

### ISSUE THREAD

**Issue by syslap73** [LSS-Manager/LSSM-V.4#667]
**Verhalten beschreiben**
Im Reiter Anpassbare Gebäudeansicht, habe ich mir einen Filter  nur "Feuerwache Kleinwache" (Bild LSS-Bug1)  hinzugefügt. Jetzt hätte ich erwartet, dass wenn ich mir in der Anzeige nur diesen Punkt anzeigen lasse, das ich auch nur noch Kleinwachen vom Typ Feuerwehr angezeigt bekomme (Bild LSS-Bug2).  Im Bild 3 sieht man das es auch mindestens 1 Kleinwache gibt. Im Bild 4 sieht man dann schön, das diese Wache nur bei Feuerwachen, aber nicht Feuerwache Kleinwache angezeigt wird.

**Wie kann man den Fehler reproduzieren?**
Da es nur ein Filter ist, kann man dies immer wieder Reproduzieren indem man die Stammdaten in den Einstellungen hinterlegt.  Kann auch mit Polizei Kleinwache gemacht werden.  Rwttunggsdienst habe ich jetzt nicht probiert.

**Erwartetes Verhalten**
In der Ansicht Gebäudeliste nur Feuerwehr Kleinwachen wenn der Filter ausgewählt ist.

**Screenshots**
Wenn möglich, füge hier Screenshots ein, die uns helfen, den Fehler schneller zu beheben
![LSS-Bug1](https://user-images.githubusercontent.com/85284011/120620140-f61c0980-c45c-11eb-9185-291eeb930e55.jpg)
![LSS-Bug2](https://user-images.githubusercontent.com/85284011/120620144-f6b4a000-c45c-11eb-9ba9-e49bf5579430.png)
![LSS-Bug3](https://user-images.githubusercontent.com/85284011/120620146-f6b4a000-c45c-11eb-8d52-88f7f70528ff.jpg)
![LSS-Bug4](https://user-images.githubusercontent.com/85284011/120620148-f74d3680-c45c-11eb-90ca-30e79da57f11.jpg)

**Sonstige Hinweise: *(bitte ergänzen)***
 - Betriebssystem: Windows 10  Pro  20H2
 - Browser: Google Chrome Version 90.0.4430.212 (Offizieller Build) (32-Bit)
 - LSSM-Version:   LSS-V4  4.2.7+20210601.2107 [stable]
 - bei Smartphones / Tabletts: Gerät:
 - Welches der Spiele spielst du?:  Leitstellenspiel
 - Dein Name im Spiel: syslap

**Sonstiges**
Es wird einfach nicht erkannt das es eine Kleinwache ist im Filter.  Bei der Übersicht im Dashboard funktioniert dies ja ohne Probleme.

**Comment by jxn-30** [comment]
Danke, schau ich mir an. Hab auch schon eine Idee, woran es liegen könnte :)

**Comment by jxn-30** [comment]
Mit commit 661fb51 ist das für Betas gefixed, hier wird dann geschlossen, sobald das ganze mit dem nächsten stable-Update für allle live geht!
