### ISSUE TITLE
[BUG]: negative values statusCounter

### ISSUE THREAD

**Issue by kdev** [LSS-Manager/LSSM-V.4#671]
**Describe what happens**
Negative unit values as well as negative percentages are displayed instead of positive number that should be correct

**How to reproduce?**
unknown/not reproducable

**Expected behavior**
Display positive numbers

**Screenshots**
![grafik](https://user-images.githubusercontent.com/42553393/120908890-6a2dfb80-c66f-11eb-8656-f69fe874f62f.png)

**Further notes: *(please complete)***
 - OS: -
 - Browser: -
 - LSSM-Version: 4.2.7
 - which of the games are you playing: could be any 

**Further**
a reload seems to fix the issue

**Comment by kdev** [comment]
@jxn-30 has created a potential fix for this issue: 9697a17

**Comment by jxn-30** [comment]
The problem does not seem to be completely solved yet. Negative values still occur from time to time, but not as often as before.

**Comment by peribaeri** [comment]
I could imagine its because of the ELW-SEG? If they are in State 5 and get immediately to State 7 bc of the elw, they might have negative values?

**Comment by jxn-30** [comment]
No, this is probably not the reason. The S5 isn't even triggered (at least on client side).
