### ISSUE TITLE
[BUG]: Umbennen von neuen Fahrzeugen bringt Fehler

### ISSUE THREAD

**Issue by monstalein** [LSS-Manager/LSSM-V.4#711]
**Verhalten beschreiben**
Umbennen von neuen gekauften Fahrzeugen führt zu Fehler.

**Wie kann man den Fehler reproduzieren?**
1. Eine BePo öffnen
2. Neues Fahrzeug kaufen
3. Fenster offen lassen und zurück zu Fahrzeuge gehen
4. Umbenennen klicken

**Erwartetes Verhalten**
Alle Fahrzeuge werden umbenannt

**Screenshots**
![grafik](https://user-images.githubusercontent.com/3227357/122881277-4808ce80-d33b-11eb-865e-e00ee2ce3d4c.png)

**Sonstige Hinweise: *(bitte ergänzen)***
 - Betriebssystem: Windows 10
 - Browser: FireFox 89.0.1
 - LSSM-Version: v4.
 - Dein Name im Spiel: Monstalein

**Comment by jxn-30** [comment]
1. Kommt aus der V3
2. Kein direkter Bug, siehe https://github.com/LSS-Manager/lss-manager-v3/issues/756

=> Close
