### ISSUE TITLE
[BUG]: WebServer problem?

### ISSUE THREAD

**Issue by monstalein** [LSS-Manager/LSSM-V.4#756]
**Describe what happens**
LSSM v4 lädt nicht mehr

**How to reproduce?**
-

**Expected behavior**
-

**Screenshots**
-

**Further notes: *(please complete)***
 Javsascript Console output:
Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://proxy.lss-manager.de/v3/stat.php. (Grund: CORS-Kopfzeile 'Access-Control-Allow-Origin' fehlt).

Laden des Moduls von "https://proxy.lss-manager.de/v4/core.js?_=1626469716609&uid=de_DE-1275684" wurde auf Grund eines nicht freigegebenen MIME-Typs ("text/html") blockiert.
www.leitstellenspiel.de
Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://proxy.lss-manager.de/v4/core.js?_=1626469716609&uid=de_DE-1275684. (Grund: CORS-Anfrage schlug fehl).

**Further**
Add further notes here

**Comment by jxn-30** [comment]
Ja, der Server ist aktuell leider down, ist bereits bekannt und in Arbeit, deshalb schließe ich hier.

**Comment by monstalein** [comment]
Perfekt - vielen dank und sorry für das wiederholte Ticket :)
