### ISSUE TITLE
[BUG]: DOMException - LSSM-Serverstatus not available

### ISSUE THREAD

**Issue by gusowski1** [LSS-Manager/LSSM-V.4#844]
**Describe what happens**
Add a detailed description on how the bug looks like
A page with an error (status.lss-manager.de) has refused the connection

**How to reproduce?**
Click ingame on "LSSM-Server-Status

**Expected behavior**
What did you expect LSS-Manager to do?
The right window is opend.

**Screenshots**
![image](https://user-images.githubusercontent.com/6065608/132948482-458f1e6c-2d6c-4ab8-a5a8-5ea96d6e25e5.png)

**Further notes: *(please complete)***
 - OS: Windows 10 latest patch level
 - Browser:  Google Chrome Version 93.0.4577.63 (Offizieller Build) (64-Bit)
 - LSSM-Version:  @version      4.3.1+CZ-DK-DE-AU-GB-US-ES-MX-FI-FR-IT-JP-KR-NO-NL-PL-BR-PT-RO-RU-SK-SE-TR-UA
 - for Smartphones / Tablets: your device: 
 - which of the games are you playing: leitstellenspiel.de
 - your ingame name: lagu

**Further**
i'm sure this is the wrong repo - but i didn't found a better one

**Comment by jxn-30** [comment]
Müsste zum #650 er related sein. Ich close mal hier.
