### ISSUE TITLE
[BUG]: Einstellungen - Seite kann nicht ohne Speichern der Änderung verlassen werden

### ISSUE THREAD

**Issue by gusowski1** [LSS-Manager/LSSM-V.4#846]
**Verhalten beschreiben**
Wenn man in den Einstellungen etwas geändert und nicht gespeichert hat, kann man das Fenster nicht über das x ohne Speichern verlassen.
Die Option wird zwar angeboten, nach klick darauf schließt sich aber nur die Hinweismeldung, nicht jedoch die Einstellungen.

**Wie kann man den Fehler reproduzieren?**
Einstellung öffnen
irgendeine Einstellung ändern
über das "x" das Menü verlassen
"Ohne speichern verlassen auswählen" 

**Erwartetes Verhalten**
Die Einstellungen werden nicht gespeichert und geschlossen.

**Screenshots**
Wenn möglich, füge hier Screenshots ein, die uns helfen, den Fehler schneller zu beheben

**Sonstige Hinweise: *(bitte ergänzen)***
 - Betriebssystem: Windows 10
 - Browser: Chrome
 - LSSM-Version: 4.3.1
 - bei Smartphones / Tabletts: Gerät:
 - Welches der Spiele spielst du?:  leitstellenspiel.de
 - Dein Name im Spiel:lagu

**Sonstiges**
Füge hier sonstige Hinweise ein.

**Comment by jxn-30** [comment]
Hmm wenn ich das so richtig im Code seh dürfte da wahrscheinlich die reset Methode der Settings kaputt sein (wie auch in #845). So spontan ohne selbst zu testen würde ich mal vom selben Grund-Fehler ausgehen.

**Comment by jxn-30** [comment]
mit a7fcedd für Betas gefixed, kommt dann mit dem nächsten stable update demnächst für alle live.
