### ISSUE TITLE
[BUG]: Error 522 Ray ID: 68d49f37896c1fba • 2021-09-11 23:19:37 UTC Connection timed out

### ISSUE THREAD

**Issue by Rene-63** [LSS-Manager/LSSM-V.4#848]
**Verhalten beschreiben**
Füge hier eine detaillierte Beschreibung ein, was genau passiert.

**Wie kann man den Fehler reproduzieren?**
Beschreibe hier, wenn möglich, was du gemacht hast, als der Fehler auftrat.
z.B.:
1. Auf '…' klicken
2. '…' eingeben
3. …
4. Das Fehlverhalten tritt auf

**Erwartetes Verhalten**
Welches Verhalten hättest du erwartet?

**Screenshots**
Wenn möglich, füge hier Screenshots ein, die uns helfen, den Fehler schneller zu beheben

**Sonstige Hinweise: *(bitte ergänzen)***
 - Betriebssystem:
 - Browser:
 - LSSM-Version:
 - bei Smartphones / Tabletts: Gerät:
 - Welches der Spiele spielst du?: 
 - Dein Name im Spiel:

**Sonstiges**
Füge hier sonstige Hinweise ein.

**Comment by Suchty112** [comment]
We are aware of the error. Should recover in the next few hours. There are a few other things running on the LSSM server :)

Uns ist der Fehler bekannt. Sollte sich in den nächsten Stunden erholen. Auf dem Server vom LSSM laufen noch ein paar andere Sachen :)
