### ISSUE TITLE
[BUG]: GW-A werden nicht erkannt

### ISSUE THREAD

**Issue by weoiss1998** [LSS-Manager/LSSM-V.4#869]
**Verhalten beschreiben**
GW-A werden bei der Auswahl weder gezählt, noch nach der Alarmierung angezeigt.

**Wie kann man den Fehler reproduzieren?**
Beschreibe hier, wenn möglich, was du gemacht hast, als der Fehler auftrat.
z.B.:
GW-A alarmieren, wenn benötigt.
**Erwartetes Verhalten**
Dass GW-A auch gezählt werden.

**Screenshots**
![GW-A Bug](https://user-images.githubusercontent.com/5202834/133624207-b6576868-042e-48cd-9ef4-36901a8c94c9.PNG)

**Sonstige Hinweise: *(bitte ergänzen)***
 - Betriebssystem: Win10
 - Browser: Firefox
 - LSSM-Version: V4
 - bei Smartphones / Tabletts: Gerät:
 - Welches der Spiele spielst du?: leitstellenspiel 
 - Dein Name im Spiel: weoiss

**Sonstiges**
Füge hier sonstige Hinweise ein.

**Comment by jxn-30** [comment]
Danke, die haben alle GW-A Texte geändert, deshalb stimmen unsre Texte nichtmehr. Ist mit 54a12a6 korrigiert, wird dann mit dem nächsten stable-Update (vsl. nächste Woche) für alle online gehen :)

**Comment by weoiss1998** [comment]
Danke für die schnelle Antwort. :)
