### ISSUE TITLE
[Feature Request]: Möglichkeit Patienten im erweiterten Alarmfenster auszublenden 

### ISSUE THREAD

**Issue by gusowski1** [LSS-Manager/LSSM-V.4#923]
Damit das erweiterte Alarmfenster immer ähnlich groß aufgebaut ist, wäre es praktisch, wenn besonders bei MANV-Einsätzen nicht alle Patienten angezeigt werden, sondern man die Möglichkeit hat, die Patienten standardmäßig einzuklappen.
Eine Zusammenfassung der Patienten bietet ja bereits die Option "Patientenzusammenfassung "

**Lösung / Feature**
Wenn mehr als 3 (oder 6 - wären dann halt 2 Reihen) Patienten vorhanden sind, werden alle Patienten ausgeblendet, und man bekommt einen optionalen Knopf um bei Bedarf die Patienten wieder einzublenden.

**Comment by jxn-30** [comment]
Für Betas ist das ganze nun umgesetzt:

![grafik](https://user-images.githubusercontent.com/27238105/145019477-815f7e7e-4112-4576-8d4f-d2157bace7a0.png)

Wird mit dem nächsten Release dann für alle freigeschalten werden.

**Comment by jxn-30** [comment]
Mit Version **4.4.3** online!
