### ISSUE TITLE
Missing PdI in the Advanced POI menu

### ISSUE THREAD

**Issue by cybermanxx** [LSS-Manager/LSSM-V.4#982]
N.B: This refers to the IT version of the game, but may be applicable to other versions
There are about 10 POI that miss in the advanced POI menu. If you create one of those 10 POIs, it doesn't appear on the map, both with and without LSSM running. 
Solution: add remaining POIs to LSSM

**Comment by Suchty112** [comment]
fixxed with https://github.com/LSS-Manager/LSSM-V.4/commit/69ef01414112dfd571a2df730f3cf591fe4163b2
Available for Beta's . For all in a few days
